"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class EvolutionCondition(_message.Message):
    """Only one of these fields will be used. We check in the order shown below"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class NestedEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___EvolutionCondition: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___EvolutionCondition | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    NUMBER_FIELD_NUMBER: _builtins.int
    FLOAT_FIELD_NUMBER: _builtins.int
    STRING_FIELD_NUMBER: _builtins.int
    NUMBERARRAY_FIELD_NUMBER: _builtins.int
    FLOATARRAY_FIELD_NUMBER: _builtins.int
    STRINGARRAY_FIELD_NUMBER: _builtins.int
    NESTED_FIELD_NUMBER: _builtins.int
    number: _builtins.int
    float: _builtins.float
    string: _builtins.str
    @_builtins.property
    def numberArray(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def floatArray(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    @_builtins.property
    def stringArray(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def nested(self) -> _containers.MessageMap[_builtins.str, Global___EvolutionCondition]: ...
    def __init__(
        self,
        *,
        number: _builtins.int | None = ...,
        float: _builtins.float | None = ...,
        string: _builtins.str | None = ...,
        numberArray: _abc.Iterable[_builtins.int] | None = ...,
        floatArray: _abc.Iterable[_builtins.float] | None = ...,
        stringArray: _abc.Iterable[_builtins.str] | None = ...,
        nested: _abc.Mapping[_builtins.str, Global___EvolutionCondition] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_float", b"_float", "_number", b"_number", "_string", b"_string", "float", b"float", "number", b"number", "string", b"string"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_float", b"_float", "_number", b"_number", "_string", b"_string", "float", b"float", "floatArray", b"floatArray", "nested", b"nested", "number", b"number", "numberArray", b"numberArray", "string", b"string", "stringArray", b"stringArray"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__float: _TypeAlias = _typing.Literal["float"]  # noqa: Y015
    _WhichOneofArgType__float: _TypeAlias = _typing.Literal["_float", b"_float"]  # noqa: Y015
    _WhichOneofReturnType__number: _TypeAlias = _typing.Literal["number"]  # noqa: Y015
    _WhichOneofArgType__number: _TypeAlias = _typing.Literal["_number", b"_number"]  # noqa: Y015
    _WhichOneofReturnType__string: _TypeAlias = _typing.Literal["string"]  # noqa: Y015
    _WhichOneofArgType__string: _TypeAlias = _typing.Literal["_string", b"_string"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__float) -> _WhichOneofReturnType__float | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__number) -> _WhichOneofReturnType__number | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__string) -> _WhichOneofReturnType__string | None: ...

Global___EvolutionCondition: _TypeAlias = EvolutionCondition  # noqa: Y015

@_typing.final
class Evolution(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ConditionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___EvolutionCondition: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___EvolutionCondition | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TO_FIELD_NUMBER: _builtins.int
    CONDITIONS_FIELD_NUMBER: _builtins.int
    FROMFORM_FIELD_NUMBER: _builtins.int
    TOFORM_FIELD_NUMBER: _builtins.int
    to: _builtins.int
    fromForm: _builtins.int
    toForm: _builtins.int
    @_builtins.property
    def conditions(self) -> _containers.MessageMap[_builtins.str, Global___EvolutionCondition]: ...
    def __init__(
        self,
        *,
        to: _builtins.int = ...,
        conditions: _abc.Mapping[_builtins.str, Global___EvolutionCondition] | None = ...,
        fromForm: _builtins.int | None = ...,
        toForm: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_fromForm", b"_fromForm", "_toForm", b"_toForm", "fromForm", b"fromForm", "toForm", b"toForm"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_fromForm", b"_fromForm", "_toForm", b"_toForm", "conditions", b"conditions", "fromForm", b"fromForm", "to", b"to", "toForm", b"toForm"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__fromForm: _TypeAlias = _typing.Literal["fromForm"]  # noqa: Y015
    _WhichOneofArgType__fromForm: _TypeAlias = _typing.Literal["_fromForm", b"_fromForm"]  # noqa: Y015
    _WhichOneofReturnType__toForm: _TypeAlias = _typing.Literal["toForm"]  # noqa: Y015
    _WhichOneofArgType__toForm: _TypeAlias = _typing.Literal["_toForm", b"_toForm"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__fromForm) -> _WhichOneofReturnType__fromForm | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__toForm) -> _WhichOneofReturnType__toForm | None: ...

Global___Evolution: _TypeAlias = Evolution  # noqa: Y015

@_typing.final
class Stats(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HP_FIELD_NUMBER: _builtins.int
    ATTACK_FIELD_NUMBER: _builtins.int
    DEFENSE_FIELD_NUMBER: _builtins.int
    SPECIALATTACK_FIELD_NUMBER: _builtins.int
    SPECIALDEFENSE_FIELD_NUMBER: _builtins.int
    SPEED_FIELD_NUMBER: _builtins.int
    hp: _builtins.int
    attack: _builtins.int
    defense: _builtins.int
    specialAttack: _builtins.int
    specialDefense: _builtins.int
    speed: _builtins.int
    def __init__(
        self,
        *,
        hp: _builtins.int | None = ...,
        attack: _builtins.int | None = ...,
        defense: _builtins.int | None = ...,
        specialAttack: _builtins.int | None = ...,
        specialDefense: _builtins.int | None = ...,
        speed: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_attack", b"_attack", "_defense", b"_defense", "_hp", b"_hp", "_specialAttack", b"_specialAttack", "_specialDefense", b"_specialDefense", "_speed", b"_speed", "attack", b"attack", "defense", b"defense", "hp", b"hp", "specialAttack", b"specialAttack", "specialDefense", b"specialDefense", "speed", b"speed"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_attack", b"_attack", "_defense", b"_defense", "_hp", b"_hp", "_specialAttack", b"_specialAttack", "_specialDefense", b"_specialDefense", "_speed", b"_speed", "attack", b"attack", "defense", b"defense", "hp", b"hp", "specialAttack", b"specialAttack", "specialDefense", b"specialDefense", "speed", b"speed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__attack: _TypeAlias = _typing.Literal["attack"]  # noqa: Y015
    _WhichOneofArgType__attack: _TypeAlias = _typing.Literal["_attack", b"_attack"]  # noqa: Y015
    _WhichOneofReturnType__defense: _TypeAlias = _typing.Literal["defense"]  # noqa: Y015
    _WhichOneofArgType__defense: _TypeAlias = _typing.Literal["_defense", b"_defense"]  # noqa: Y015
    _WhichOneofReturnType__hp: _TypeAlias = _typing.Literal["hp"]  # noqa: Y015
    _WhichOneofArgType__hp: _TypeAlias = _typing.Literal["_hp", b"_hp"]  # noqa: Y015
    _WhichOneofReturnType__specialAttack: _TypeAlias = _typing.Literal["specialAttack"]  # noqa: Y015
    _WhichOneofArgType__specialAttack: _TypeAlias = _typing.Literal["_specialAttack", b"_specialAttack"]  # noqa: Y015
    _WhichOneofReturnType__specialDefense: _TypeAlias = _typing.Literal["specialDefense"]  # noqa: Y015
    _WhichOneofArgType__specialDefense: _TypeAlias = _typing.Literal["_specialDefense", b"_specialDefense"]  # noqa: Y015
    _WhichOneofReturnType__speed: _TypeAlias = _typing.Literal["speed"]  # noqa: Y015
    _WhichOneofArgType__speed: _TypeAlias = _typing.Literal["_speed", b"_speed"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__attack) -> _WhichOneofReturnType__attack | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__defense) -> _WhichOneofReturnType__defense | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__hp) -> _WhichOneofReturnType__hp | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__specialAttack) -> _WhichOneofReturnType__specialAttack | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__specialDefense) -> _WhichOneofReturnType__specialDefense | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__speed) -> _WhichOneofReturnType__speed | None: ...

Global___Stats: _TypeAlias = Stats  # noqa: Y015

@_typing.final
class Sprites(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PARTY_FIELD_NUMBER: _builtins.int
    NORMAL_FIELD_NUMBER: _builtins.int
    SHINY_FIELD_NUMBER: _builtins.int
    FEMALE_FIELD_NUMBER: _builtins.int
    FEMALESHINY_FIELD_NUMBER: _builtins.int
    party: _builtins.str
    normal: _builtins.str
    shiny: _builtins.str
    female: _builtins.str
    femaleShiny: _builtins.str
    def __init__(
        self,
        *,
        party: _builtins.str = ...,
        normal: _builtins.str = ...,
        shiny: _builtins.str = ...,
        female: _builtins.str | None = ...,
        femaleShiny: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_female", b"_female", "_femaleShiny", b"_femaleShiny", "female", b"female", "femaleShiny", b"femaleShiny"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_female", b"_female", "_femaleShiny", b"_femaleShiny", "female", b"female", "femaleShiny", b"femaleShiny", "normal", b"normal", "party", b"party", "shiny", b"shiny"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__female: _TypeAlias = _typing.Literal["female"]  # noqa: Y015
    _WhichOneofArgType__female: _TypeAlias = _typing.Literal["_female", b"_female"]  # noqa: Y015
    _WhichOneofReturnType__femaleShiny: _TypeAlias = _typing.Literal["femaleShiny"]  # noqa: Y015
    _WhichOneofArgType__femaleShiny: _TypeAlias = _typing.Literal["_femaleShiny", b"_femaleShiny"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__female) -> _WhichOneofReturnType__female | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__femaleShiny) -> _WhichOneofReturnType__femaleShiny | None: ...

Global___Sprites: _TypeAlias = Sprites  # noqa: Y015

@_typing.final
class Species(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    SPRITES_FIELD_NUMBER: _builtins.int
    GAMEID_FIELD_NUMBER: _builtins.int
    FORM_FIELD_NUMBER: _builtins.int
    FORMNAME_FIELD_NUMBER: _builtins.int
    BASESTATS_FIELD_NUMBER: _builtins.int
    BASEFRIENDSHIP_FIELD_NUMBER: _builtins.int
    EVYIELD_FIELD_NUMBER: _builtins.int
    ABILITIES_FIELD_NUMBER: _builtins.int
    COLOR_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    WEIGHT_FIELD_NUMBER: _builtins.int
    HATCHCYCLES_FIELD_NUMBER: _builtins.int
    GENDERRATIO_FIELD_NUMBER: _builtins.int
    CATCHRATE_FIELD_NUMBER: _builtins.int
    TYPES_FIELD_NUMBER: _builtins.int
    GROWTHRATE_FIELD_NUMBER: _builtins.int
    EVOLUTIONS_FIELD_NUMBER: _builtins.int
    FORMS_FIELD_NUMBER: _builtins.int
    MAXHEARTGAUGE_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    name: _builtins.str
    gameId: _builtins.int
    form: _builtins.int
    formName: _builtins.str
    baseFriendship: _builtins.int
    color: _builtins.str
    height: _builtins.int
    weight: _builtins.int
    hatchCycles: _builtins.int
    genderRatio: _builtins.int
    catchRate: _builtins.int
    growthRate: _builtins.int
    maxHeartGauge: _builtins.int
    @_builtins.property
    def sprites(self) -> Global___Sprites: ...
    @_builtins.property
    def baseStats(self) -> Global___Stats: ...
    @_builtins.property
    def evYield(self) -> Global___Stats: ...
    @_builtins.property
    def abilities(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def types(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def evolutions(self) -> _containers.RepeatedCompositeFieldContainer[Global___Evolution]: ...
    @_builtins.property
    def forms(self) -> _containers.RepeatedCompositeFieldContainer[Global___Species]: ...
    def __init__(
        self,
        *,
        id: _builtins.int | None = ...,
        name: _builtins.str = ...,
        sprites: Global___Sprites | None = ...,
        gameId: _builtins.int | None = ...,
        form: _builtins.int | None = ...,
        formName: _builtins.str | None = ...,
        baseStats: Global___Stats | None = ...,
        baseFriendship: _builtins.int | None = ...,
        evYield: Global___Stats | None = ...,
        abilities: _abc.Iterable[_builtins.str] | None = ...,
        color: _builtins.str | None = ...,
        height: _builtins.int | None = ...,
        weight: _builtins.int | None = ...,
        hatchCycles: _builtins.int | None = ...,
        genderRatio: _builtins.int | None = ...,
        catchRate: _builtins.int = ...,
        types: _abc.Iterable[_builtins.str] | None = ...,
        growthRate: _builtins.int = ...,
        evolutions: _abc.Iterable[Global___Evolution] | None = ...,
        forms: _abc.Iterable[Global___Species] | None = ...,
        maxHeartGauge: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_baseFriendship", b"_baseFriendship", "_color", b"_color", "_evYield", b"_evYield", "_form", b"_form", "_formName", b"_formName", "_gameId", b"_gameId", "_genderRatio", b"_genderRatio", "_hatchCycles", b"_hatchCycles", "_height", b"_height", "_id", b"_id", "_maxHeartGauge", b"_maxHeartGauge", "_weight", b"_weight", "baseFriendship", b"baseFriendship", "baseStats", b"baseStats", "color", b"color", "evYield", b"evYield", "form", b"form", "formName", b"formName", "gameId", b"gameId", "genderRatio", b"genderRatio", "hatchCycles", b"hatchCycles", "height", b"height", "id", b"id", "maxHeartGauge", b"maxHeartGauge", "sprites", b"sprites", "weight", b"weight"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_baseFriendship", b"_baseFriendship", "_color", b"_color", "_evYield", b"_evYield", "_form", b"_form", "_formName", b"_formName", "_gameId", b"_gameId", "_genderRatio", b"_genderRatio", "_hatchCycles", b"_hatchCycles", "_height", b"_height", "_id", b"_id", "_maxHeartGauge", b"_maxHeartGauge", "_weight", b"_weight", "abilities", b"abilities", "baseFriendship", b"baseFriendship", "baseStats", b"baseStats", "catchRate", b"catchRate", "color", b"color", "evYield", b"evYield", "evolutions", b"evolutions", "form", b"form", "formName", b"formName", "forms", b"forms", "gameId", b"gameId", "genderRatio", b"genderRatio", "growthRate", b"growthRate", "hatchCycles", b"hatchCycles", "height", b"height", "id", b"id", "maxHeartGauge", b"maxHeartGauge", "name", b"name", "sprites", b"sprites", "types", b"types", "weight", b"weight"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__baseFriendship: _TypeAlias = _typing.Literal["baseFriendship"]  # noqa: Y015
    _WhichOneofArgType__baseFriendship: _TypeAlias = _typing.Literal["_baseFriendship", b"_baseFriendship"]  # noqa: Y015
    _WhichOneofReturnType__color: _TypeAlias = _typing.Literal["color"]  # noqa: Y015
    _WhichOneofArgType__color: _TypeAlias = _typing.Literal["_color", b"_color"]  # noqa: Y015
    _WhichOneofReturnType__evYield: _TypeAlias = _typing.Literal["evYield"]  # noqa: Y015
    _WhichOneofArgType__evYield: _TypeAlias = _typing.Literal["_evYield", b"_evYield"]  # noqa: Y015
    _WhichOneofReturnType__form: _TypeAlias = _typing.Literal["form"]  # noqa: Y015
    _WhichOneofArgType__form: _TypeAlias = _typing.Literal["_form", b"_form"]  # noqa: Y015
    _WhichOneofReturnType__formName: _TypeAlias = _typing.Literal["formName"]  # noqa: Y015
    _WhichOneofArgType__formName: _TypeAlias = _typing.Literal["_formName", b"_formName"]  # noqa: Y015
    _WhichOneofReturnType__gameId: _TypeAlias = _typing.Literal["gameId"]  # noqa: Y015
    _WhichOneofArgType__gameId: _TypeAlias = _typing.Literal["_gameId", b"_gameId"]  # noqa: Y015
    _WhichOneofReturnType__genderRatio: _TypeAlias = _typing.Literal["genderRatio"]  # noqa: Y015
    _WhichOneofArgType__genderRatio: _TypeAlias = _typing.Literal["_genderRatio", b"_genderRatio"]  # noqa: Y015
    _WhichOneofReturnType__hatchCycles: _TypeAlias = _typing.Literal["hatchCycles"]  # noqa: Y015
    _WhichOneofArgType__hatchCycles: _TypeAlias = _typing.Literal["_hatchCycles", b"_hatchCycles"]  # noqa: Y015
    _WhichOneofReturnType__height: _TypeAlias = _typing.Literal["height"]  # noqa: Y015
    _WhichOneofArgType__height: _TypeAlias = _typing.Literal["_height", b"_height"]  # noqa: Y015
    _WhichOneofReturnType__id: _TypeAlias = _typing.Literal["id"]  # noqa: Y015
    _WhichOneofArgType__id: _TypeAlias = _typing.Literal["_id", b"_id"]  # noqa: Y015
    _WhichOneofReturnType__maxHeartGauge: _TypeAlias = _typing.Literal["maxHeartGauge"]  # noqa: Y015
    _WhichOneofArgType__maxHeartGauge: _TypeAlias = _typing.Literal["_maxHeartGauge", b"_maxHeartGauge"]  # noqa: Y015
    _WhichOneofReturnType__weight: _TypeAlias = _typing.Literal["weight"]  # noqa: Y015
    _WhichOneofArgType__weight: _TypeAlias = _typing.Literal["_weight", b"_weight"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__baseFriendship) -> _WhichOneofReturnType__baseFriendship | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__color) -> _WhichOneofReturnType__color | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__evYield) -> _WhichOneofReturnType__evYield | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__form) -> _WhichOneofReturnType__form | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__formName) -> _WhichOneofReturnType__formName | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__gameId) -> _WhichOneofReturnType__gameId | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__genderRatio) -> _WhichOneofReturnType__genderRatio | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__hatchCycles) -> _WhichOneofReturnType__hatchCycles | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__height) -> _WhichOneofReturnType__height | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__id) -> _WhichOneofReturnType__id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__maxHeartGauge) -> _WhichOneofReturnType__maxHeartGauge | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__weight) -> _WhichOneofReturnType__weight | None: ...

Global___Species: _TypeAlias = Species  # noqa: Y015

@_typing.final
class Pokedex(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VERSION_FIELD_NUMBER: _builtins.int
    ENTRIES_FIELD_NUMBER: _builtins.int
    version: _builtins.str
    @_builtins.property
    def entries(self) -> _containers.RepeatedCompositeFieldContainer[Global___Species]: ...
    def __init__(
        self,
        *,
        version: _builtins.str = ...,
        entries: _abc.Iterable[Global___Species] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entries", b"entries", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Pokedex: _TypeAlias = Pokedex  # noqa: Y015
