"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class EvolutionCondition(google.protobuf.message.Message):
    """Only one of these fields will be used. We check in the order shown below"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class NestedEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___EvolutionCondition: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___EvolutionCondition | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    NUMBER_FIELD_NUMBER: builtins.int
    FLOAT_FIELD_NUMBER: builtins.int
    STRING_FIELD_NUMBER: builtins.int
    NUMBERARRAY_FIELD_NUMBER: builtins.int
    FLOATARRAY_FIELD_NUMBER: builtins.int
    STRINGARRAY_FIELD_NUMBER: builtins.int
    NESTED_FIELD_NUMBER: builtins.int
    number: builtins.int
    float: builtins.float
    string: builtins.str
    @property
    def numberArray(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def floatArray(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def stringArray(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def nested(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___EvolutionCondition]: ...
    def __init__(
        self,
        *,
        number: builtins.int | None = ...,
        float: builtins.float | None = ...,
        string: builtins.str | None = ...,
        numberArray: collections.abc.Iterable[builtins.int] | None = ...,
        floatArray: collections.abc.Iterable[builtins.float] | None = ...,
        stringArray: collections.abc.Iterable[builtins.str] | None = ...,
        nested: collections.abc.Mapping[builtins.str, global___EvolutionCondition] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_float", b"_float", "_number", b"_number", "_string", b"_string", "float", b"float", "number", b"number", "string", b"string"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_float", b"_float", "_number", b"_number", "_string", b"_string", "float", b"float", "floatArray", b"floatArray", "nested", b"nested", "number", b"number", "numberArray", b"numberArray", "string", b"string", "stringArray", b"stringArray"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_float", b"_float"]) -> typing.Literal["float"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_number", b"_number"]) -> typing.Literal["number"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_string", b"_string"]) -> typing.Literal["string"] | None: ...

global___EvolutionCondition = EvolutionCondition

@typing.final
class Evolution(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ConditionsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___EvolutionCondition: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___EvolutionCondition | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    TO_FIELD_NUMBER: builtins.int
    CONDITIONS_FIELD_NUMBER: builtins.int
    FROMFORM_FIELD_NUMBER: builtins.int
    TOFORM_FIELD_NUMBER: builtins.int
    to: builtins.int
    fromForm: builtins.int
    toForm: builtins.int
    @property
    def conditions(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___EvolutionCondition]: ...
    def __init__(
        self,
        *,
        to: builtins.int = ...,
        conditions: collections.abc.Mapping[builtins.str, global___EvolutionCondition] | None = ...,
        fromForm: builtins.int | None = ...,
        toForm: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_fromForm", b"_fromForm", "_toForm", b"_toForm", "fromForm", b"fromForm", "toForm", b"toForm"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_fromForm", b"_fromForm", "_toForm", b"_toForm", "conditions", b"conditions", "fromForm", b"fromForm", "to", b"to", "toForm", b"toForm"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_fromForm", b"_fromForm"]) -> typing.Literal["fromForm"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_toForm", b"_toForm"]) -> typing.Literal["toForm"] | None: ...

global___Evolution = Evolution

@typing.final
class Stats(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HP_FIELD_NUMBER: builtins.int
    ATTACK_FIELD_NUMBER: builtins.int
    DEFENSE_FIELD_NUMBER: builtins.int
    SPECIALATTACK_FIELD_NUMBER: builtins.int
    SPECIALDEFENSE_FIELD_NUMBER: builtins.int
    SPEED_FIELD_NUMBER: builtins.int
    hp: builtins.int
    attack: builtins.int
    defense: builtins.int
    specialAttack: builtins.int
    specialDefense: builtins.int
    speed: builtins.int
    def __init__(
        self,
        *,
        hp: builtins.int | None = ...,
        attack: builtins.int | None = ...,
        defense: builtins.int | None = ...,
        specialAttack: builtins.int | None = ...,
        specialDefense: builtins.int | None = ...,
        speed: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_attack", b"_attack", "_defense", b"_defense", "_hp", b"_hp", "_specialAttack", b"_specialAttack", "_specialDefense", b"_specialDefense", "_speed", b"_speed", "attack", b"attack", "defense", b"defense", "hp", b"hp", "specialAttack", b"specialAttack", "specialDefense", b"specialDefense", "speed", b"speed"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_attack", b"_attack", "_defense", b"_defense", "_hp", b"_hp", "_specialAttack", b"_specialAttack", "_specialDefense", b"_specialDefense", "_speed", b"_speed", "attack", b"attack", "defense", b"defense", "hp", b"hp", "specialAttack", b"specialAttack", "specialDefense", b"specialDefense", "speed", b"speed"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_attack", b"_attack"]) -> typing.Literal["attack"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_defense", b"_defense"]) -> typing.Literal["defense"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_hp", b"_hp"]) -> typing.Literal["hp"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_specialAttack", b"_specialAttack"]) -> typing.Literal["specialAttack"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_specialDefense", b"_specialDefense"]) -> typing.Literal["specialDefense"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_speed", b"_speed"]) -> typing.Literal["speed"] | None: ...

global___Stats = Stats

@typing.final
class Sprites(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARTY_FIELD_NUMBER: builtins.int
    NORMAL_FIELD_NUMBER: builtins.int
    SHINY_FIELD_NUMBER: builtins.int
    FEMALE_FIELD_NUMBER: builtins.int
    FEMALESHINY_FIELD_NUMBER: builtins.int
    party: builtins.str
    normal: builtins.str
    shiny: builtins.str
    female: builtins.str
    femaleShiny: builtins.str
    def __init__(
        self,
        *,
        party: builtins.str = ...,
        normal: builtins.str = ...,
        shiny: builtins.str = ...,
        female: builtins.str | None = ...,
        femaleShiny: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_female", b"_female", "_femaleShiny", b"_femaleShiny", "female", b"female", "femaleShiny", b"femaleShiny"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_female", b"_female", "_femaleShiny", b"_femaleShiny", "female", b"female", "femaleShiny", b"femaleShiny", "normal", b"normal", "party", b"party", "shiny", b"shiny"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_female", b"_female"]) -> typing.Literal["female"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_femaleShiny", b"_femaleShiny"]) -> typing.Literal["femaleShiny"] | None: ...

global___Sprites = Sprites

@typing.final
class Species(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    SPRITES_FIELD_NUMBER: builtins.int
    GAMEID_FIELD_NUMBER: builtins.int
    FORM_FIELD_NUMBER: builtins.int
    FORMNAME_FIELD_NUMBER: builtins.int
    BASESTATS_FIELD_NUMBER: builtins.int
    BASEFRIENDSHIP_FIELD_NUMBER: builtins.int
    EVYIELD_FIELD_NUMBER: builtins.int
    ABILITIES_FIELD_NUMBER: builtins.int
    COLOR_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    WEIGHT_FIELD_NUMBER: builtins.int
    HATCHCYCLES_FIELD_NUMBER: builtins.int
    GENDERRATIO_FIELD_NUMBER: builtins.int
    CATCHRATE_FIELD_NUMBER: builtins.int
    TYPES_FIELD_NUMBER: builtins.int
    GROWTHRATE_FIELD_NUMBER: builtins.int
    EVOLUTIONS_FIELD_NUMBER: builtins.int
    FORMS_FIELD_NUMBER: builtins.int
    id: builtins.int
    name: builtins.str
    gameId: builtins.int
    form: builtins.int
    formName: builtins.str
    baseFriendship: builtins.int
    color: builtins.str
    height: builtins.int
    weight: builtins.int
    hatchCycles: builtins.int
    genderRatio: builtins.int
    catchRate: builtins.int
    growthRate: builtins.int
    @property
    def sprites(self) -> global___Sprites: ...
    @property
    def baseStats(self) -> global___Stats: ...
    @property
    def evYield(self) -> global___Stats: ...
    @property
    def abilities(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def types(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def evolutions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Evolution]: ...
    @property
    def forms(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Species]: ...
    def __init__(
        self,
        *,
        id: builtins.int | None = ...,
        name: builtins.str = ...,
        sprites: global___Sprites | None = ...,
        gameId: builtins.int | None = ...,
        form: builtins.int | None = ...,
        formName: builtins.str | None = ...,
        baseStats: global___Stats | None = ...,
        baseFriendship: builtins.int | None = ...,
        evYield: global___Stats | None = ...,
        abilities: collections.abc.Iterable[builtins.str] | None = ...,
        color: builtins.str | None = ...,
        height: builtins.int | None = ...,
        weight: builtins.int | None = ...,
        hatchCycles: builtins.int | None = ...,
        genderRatio: builtins.int | None = ...,
        catchRate: builtins.int = ...,
        types: collections.abc.Iterable[builtins.str] | None = ...,
        growthRate: builtins.int = ...,
        evolutions: collections.abc.Iterable[global___Evolution] | None = ...,
        forms: collections.abc.Iterable[global___Species] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_baseFriendship", b"_baseFriendship", "_color", b"_color", "_evYield", b"_evYield", "_form", b"_form", "_formName", b"_formName", "_gameId", b"_gameId", "_genderRatio", b"_genderRatio", "_hatchCycles", b"_hatchCycles", "_height", b"_height", "_id", b"_id", "_weight", b"_weight", "baseFriendship", b"baseFriendship", "baseStats", b"baseStats", "color", b"color", "evYield", b"evYield", "form", b"form", "formName", b"formName", "gameId", b"gameId", "genderRatio", b"genderRatio", "hatchCycles", b"hatchCycles", "height", b"height", "id", b"id", "sprites", b"sprites", "weight", b"weight"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_baseFriendship", b"_baseFriendship", "_color", b"_color", "_evYield", b"_evYield", "_form", b"_form", "_formName", b"_formName", "_gameId", b"_gameId", "_genderRatio", b"_genderRatio", "_hatchCycles", b"_hatchCycles", "_height", b"_height", "_id", b"_id", "_weight", b"_weight", "abilities", b"abilities", "baseFriendship", b"baseFriendship", "baseStats", b"baseStats", "catchRate", b"catchRate", "color", b"color", "evYield", b"evYield", "evolutions", b"evolutions", "form", b"form", "formName", b"formName", "forms", b"forms", "gameId", b"gameId", "genderRatio", b"genderRatio", "growthRate", b"growthRate", "hatchCycles", b"hatchCycles", "height", b"height", "id", b"id", "name", b"name", "sprites", b"sprites", "types", b"types", "weight", b"weight"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_baseFriendship", b"_baseFriendship"]) -> typing.Literal["baseFriendship"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_color", b"_color"]) -> typing.Literal["color"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_evYield", b"_evYield"]) -> typing.Literal["evYield"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_form", b"_form"]) -> typing.Literal["form"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_formName", b"_formName"]) -> typing.Literal["formName"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_gameId", b"_gameId"]) -> typing.Literal["gameId"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_genderRatio", b"_genderRatio"]) -> typing.Literal["genderRatio"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_hatchCycles", b"_hatchCycles"]) -> typing.Literal["hatchCycles"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_height", b"_height"]) -> typing.Literal["height"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_id", b"_id"]) -> typing.Literal["id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_weight", b"_weight"]) -> typing.Literal["weight"] | None: ...

global___Species = Species

@typing.final
class Pokedex(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    ENTRIES_FIELD_NUMBER: builtins.int
    version: builtins.str
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Species]: ...
    def __init__(
        self,
        *,
        version: builtins.str = ...,
        entries: collections.abc.Iterable[global___Species] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["entries", b"entries", "version", b"version"]) -> None: ...

global___Pokedex = Pokedex
