import pokelink.translations as translations
import pokelink.game_strings as game_strings
import pokelink.directories as directories
import os

from pokelink.json_output import write_file

_items = [
    None, "Poké Ball", "Great Ball", "Ultra Ball",
    "Master Ball", "Premier Ball", "Heal Ball", "Net Ball",
    "Nest Ball", "Dive Ball", "Dusk Ball", "Timer Ball",
    "Quick Ball", "Repeat Ball", "Luxury Ball", "Level Ball",
    "Lure Ball", "Moon Ball", "Friend Ball", "Love Ball",
    "Fast Ball", "Heavy Ball", "Dream Ball", "Safari Ball",
    "Sport Ball", "Park Ball", "Beast Ball", "Cherish Ball",
    "Potion", "Super Potion", "Hyper Potion", "Max Potion",
    "Full Restore", "Revive", "Max Revive", "Fresh Water",
    "Soda Pop", "Lemonade", "Moomoo Milk", "Energy Powder",
    "Energy Root", "Heal Powder", "Revival Herb", "Antidote",
    "Paralyze Heal", "Burn Heal", "Ice Heal", "Awakening",
    "Full Heal", "Ether", "Max Ether", "Elixir",
    "Max Elixir", "Berry Juice", "Sacred Ash", "Sweet Heart",
    "Max Honey", "Pewter Crunchies", "Rage Candy Bar", "Lava Cookie",
    "Old Gateau", "Casteliacone", "Lumiose Galette", "Shalour Sable",
    "Big Malasada", "HP Up", "Protein", "Iron",
    "Calcium", "Zinc", "Carbos", "PP Up",
    "PP Max", "Health Feather", "Muscle Feather", "Resist Feather",
    "Genius Feather", "Clever Feather", "Swift Feather", "Ability Capsule",
    "Ability Patch", "Lonely Mint", "Adamant Mint", "Naughty Mint",
    "Brave Mint", "Bold Mint", "Impish Mint", "Lax Mint",
    "Relaxed Mint", "Modest Mint", "Mild Mint", "Rash Mint",
    "Quiet Mint", "Calm Mint", "Gentle Mint", "Careful Mint",
    "Sassy Mint", "Timid Mint", "Hasty Mint", "Jolly Mint",
    "Naive Mint", "Serious Mint", "Rare Candy", "EXP Candy XS",
    "EXP Candy S", "EXP Candy M", "EXP Candy L", "EXP Candy XL",
    "Blue Flute", "Yellow Flute", "Red Flute", "Black Flute",
    "White Flute", "Repel", "Super Repel", "Max Repel",
    "Lure", " Super Lure", "Max Lure", "Escape Rope",
    "X Attack", "X Defense", "X Special Attack", "X Special Defend",
    "X Accuracy", "Poké Doll", "Fluffy Tail", "Poké Toy",
    "Max Mushrooms", "Unknown", "Unknown", "Unknown",
    "Unknown", "Bottle Cap", "Gold Bottle Cap", "Nugget",
    "Big Nugget", "Tiny Mushroom", "Big Mushroom", "Balm Mushroom",
    "Pearl", "Big Pearl", "Pearl String", "Stardust",
    "Star Piece", "Comet Shard", "Shoal Salt", "Shoal Shell",
    "Red Shard", "Blue Shard", "Yellow Shard", "Green Shard",
    "Heart Scale", "Honey", "Rare Bone", "Odd Keystone",
    "Pretty Feather", "Relic Copper", "Relic Silver", "Relic Gold",
    "Relic Vase", "Relic Band", "Relic Statue", "Relic Crown",
    "Strange Souvenir", "Helix Fossil", "Dome Fossil", "Old Amber",
    "Root Fossil", "Claw Fossil", "Armor Fossil", "Skull Fossil",
    "Cover Fossil", "Plume Fossil", "Jaw Fossil", "Sail Fossil",
    "Fossilized Bird", "Fossilized Fish", "Fossilized Drake", "Fossilized Dino",
    "Growth Mulch", "Damp Mulch", "Stable Mulch", "Gooey Mulch",
    "Rich Mulch", "Surprise Mulch", "Boost Mulch", "Amaze Mulch",
    "Red Apricorn", "Blue Apricorn", "Yellow Apricorn", "Green Apricorn",
    "Pink Apricorn", "White Apricorn", "Black Apricorn", "Wishing Piece",
    "Galarica Twig", "Armorite Ore", "Dynite Ore", "Orange Mail",
    "Harbor Mail", "Glitter Mail", "Mech Mail", "Wood Mail",
    "Wave Mail", "Bead Mail", "Shadow Mail", "Tropic Mail",
    "Dream Mail", "Fab Mail", "Retro Mail", "Fire Stone",
    "Water Stone", "Thunder Stone", "Leaf Stone", "Ice Stone",
    "Sun Stone", "Moon Stone", "Shiny Stone", "Dusk Stone",
    "Dawn Stone", "Sweet Apple", "Tart Apple", "Cracked Pot",
    "Chipped Pot", "Galarica Cuff", "Galarica Wreath", "Dragon Scale",
    "Up-Grade", "Protector", "Electirizer", "Magmarizer",
    "Dubious Disc", "Reaper Cloth", "Prism Scale", "Whipped Dream",
    "Sachet", "Oval Stone", "Strawberry Sweet", "Love Sweet",
    "Berry Sweet", "Clover Sweet", "Flower Sweet", "Star Sweet",
    "Ribbon Sweet", "Everstone", "Red Nectar", "Yellow Nectar",
    "Pink Nectar", "Purple Nectar", "Flame Plate", "Splash Plate",
    "Zap Plate", "Meadow Plate", "Icicle Plate", "Fist Plate",
    "Toxic Plate", "Earth Plate", "Sky Plate", "Mind Plate",
    "Insect Plate", "Stone Plate", "Spooky Plate", "Draco Plate",
    "Dread Plate", "Iron Plate", "Pixie Plate", "Douse Drive",
    "Shock Drive", "Burn Drive", "Chill Drive", "Fire Memory",
    "Water Memory", "Electric Memory", "Grass Memory", "Ice Memory",
    "Fighting Memory", "Poison Memory", "Ground Memory", "Flying Memory",
    "Psychic Memory", "Bug Memory", "Rock Memory", "Ghost Memory",
    "Dragon Memory", "Dark Memory", "Steel Memory", "Fairy Memory",
    "Rusted Sword", "Rusted Shield", "Red Orb", "Blue Orb",
    "Venusaurite", "Charizardite X", "Charizardite Y", "Blastoisinite",
    "Beedrillite", "Pidgeotite", "Alakazite", "Slowbronite",
    "Gengarite", "Kangaskhanite", "Pinsirite", "Gyaradosite",
    "Aerodactylite", "Mewtwonite X", "Mewtwonite Y", "Ampharosite",
    "Steelixite", "Scizorite", "Heracronite", "Houndoominite",
    "Tyranitarite", "Sceptilite", "Blazikenite", "Swampertite",
    "Gardevoirite", "Sablenite", "Mawilite", "Aggronite",
    "Medichamite", "Manectite", "Sharpedonite", "Cameruptite",
    "Altarianite", "Banettite", "Absolite", "Glalitite",
    "Salamencite", "Metagrossite", "Latiasite", "Latiosite",
    "Lopunnite", "Garchompite", "Lucarionite", "Abomasite",
    "Galladite", "Audinite", "Diancite", "Normal Gem",
    "Fire Gem", "Water Gem", "Electric Gem", "Grass Gem",
    "Ice Gem", "Fighting Gem", "Poison Gem", "Ground Gem",
    "Flying Gem", "Psychic Gem", "Bug Gem", "Rock Gem",
    "Ghost Gem", "Dragon Gem", "Dark Gem", "Steel Gem",
    "Fairy Gem", "Normalium Z", "Firium Z", "Waterium Z",
    "Electrium Z", "Grassium Z", "Icium Z", "Fightinium Z",
    "Poisonium Z", "Groundium Z", "Flyinium Z", "Psychium Z",
    "Buginium Z", "Rockium Z", "Ghostium Z", "Dragonium Z",
    "Darkinium Z", "Steelium Z", "Fairium Z", "Pikanium Z",
    "Eevium Z", "Snorlium Z", "Mewnium Z", "Decidium Z",
    "Incinium Z", "Primarium Z", "Lycanium Z", "Mimikium Z",
    "Kommonium Z", "Tapunium Z", "Solganium Z", "Lunalium Z",
    "Marshadium Z", "Aloraichium Z", "Pikashunium Z", "Ultranecrozium Z",
    "Light Ball", "Leek", "Thick Club", "Lucky Punch",
    "Metal Powder", "Quick Powder", "Deep Sea Scale", "Deep Sea Tooth",
    "Soul Dew", "Adamant Orb", "Lustrous Orb", "Griseous Orb",
    "Sea Incense", "Lax Incense", "Odd Incense", "Rock Incense",
    "Full Incense", "Wave Incense", "Rose Incense", "Luck Incense",
    "Pure Incense", "Red Scarf", "Blue Scarf", "Pink Scarf",
    "Green Scarf", "Yellow Scarf", "Macho Brace", "Power Weight",
    "Power Bracer", "Power Belt", "Power Lens", "Power Band",
    "Power Anklet", "Silk Scarf", "Charcoal", "Mystic Water",
    "Magnet", "Miracle Seed", "Never-Melt Ice", "Black Belt",
    "Poison Barb", "Soft Sand", "Sharp Beak", "Twisted Spoon",
    "Silver Powder", "Hard Stone", "Spell Tag", "Dragon Fang",
    "Black Glasses", "Metal Coat", "Choice Band", "Choice Specs",
    "Choice Scarf", "Flame Orb", "Toxic Orb", "Damp Rock",
    "Heat Rock", "Smooth Rock", "Icy Rock", "Electric Seed",
    "Psychic Seed", "Misty Seed", "Grassy Seed", "Absorb Bulb",
    "Cell Battery", "Luminous Moss", "Snowball", "Bright Powder",
    "White Herb", "EXP Share", "Quick Claw", "Soothe Bell",
    "Mental Herb", "King's Rock", "Amulet Coin", "Cleanse Tag",
    "Smoke ball", "Focus Band", "", "Scope Lens",
    "Leftovers", "Shell Bell", "Wide Lens", "Muscle Band",
    "Wise Glasses", "Expert Belt", "Light Clay", "Life Orb",
    "Power Herb", "Focus Sash", "Zoom Lens", "Metronome",
    "Iron Ball", "Lagging Tail", "Destiny Knot", "Black Sludge",
    "Grip Claw", "Sticky Barb", "Shed Shell", "Big Root",
    "Razor Claw", "Razor Fang", "Eviolite", "Float Stone",
    "Rocky Helmet", "Air Balloon", "Red Card", "Ring Target",
    "Binding Band", "Eject Button", "Weakness Policy", "Assault Vest",
    "Safety Goggles", "Adrenaline Orb", "Terrain Extender", "Protective Pads",
    "Throat Spray", "Eject Pack", "Heavy-Duty Boots", "Blunder Policy",
    "Room Service", "Utility Umbrella", "Cheri Berry", "Chesto Berry",
    "Pecha Berry", "Rawst Berry", "Aspear Berry", "Leppa Berry",
    "Oran Berry", "Persim Berry", "Lum Berry", "Sitrus Berry",
    "Figy Berry", "Wiki Berry", "Mago Berry", "Aguav Berry",
    "Iapapa Berry", "Razz Berry", "Bluk Berry", "Nanab Berry",
    "Wepear Berry", "Pinap Berry", "Pomeg Berry", "Kelpsy Berry",
    "Qualot Berry", "Hondew Berry", "Grepa Berry", "Tamato Berry",
    "Cornn Berry", "Magost Berry", "Rabuta Berry", "Nomel Berry",
    "Spelon Berry", "Pamtre Berry", "Watmel Berry", "Durin Berry",
    "Belue Berry", "Chilan Berry", "Occa Berry", "Passho Berry",
    "Wacan Berry", "Rindo Berry", "Yache Berry", "Chople Berry",
    "Kebia Berry", "Shuca Berry", "Coba Berry", "Payapa Berry",
    "Tanga Berry", "Charti Berry", "Kasib Berry", "Haban Berry",
    "Colbur Berry", "Babiri Berry", "Roseli Berry", "Liechi Berry",
    "Ganlon Berry", "Salac Berry", "Petaya Berry", "Apicot Berry",
    "Lansat Berry", "Starf Berry", "Enigma Berry", "Micle Berry",
    "Custap Berry", "Jaboca Berry", "Rowap Berry", "Kee Berry",
    "Maranga Berry", None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, None, None,
    None, None, "Unknown", "Unknown",
    "Unknown"
]

def generate_items():
    print("Generating Items")

    items_prefix = "Run&Bun.Item."

    i = {}
    it = []
    i["items"] = it

    for item in _items:
        if item is None:
            it.append(None)
            continue

        translations.add_translation(items_prefix + game_strings.clean_up(item), item)
        it.append(items_prefix + game_strings.clean_up(item))

    write_file(os.path.join(directories.get_output_dir("runAndBun"), "rb.items"), i)