import pokelink.game_strings as game_strings
import pokelink.translations as translations
import pokelink.core_plugin as core_plugin
import pokelink.directories as directories
import os

from pokelink.json_output import write_file

_pokemon = [
    "Bulbasaur", "Ivysaur", "Venusaur", "Charmander",
    "Charmeleon", "Charizard", "Squirtle", "Wartortle",
    "Blastoise", "Caterpie", "Metapod", "Butterfree",
    "Weedle", "Kakuna", "Beedrill", "Pidgey",
    "Pidgeotto", "Pidgeot", "Rattata", "Raticate",
    "Spearow", "Fearow", "Ekans", "Arbok",
    "Pikachu", "Raichu", "Sandshrew", "Sandslash",
    "Nidoran♀", "Nidorina", "Nidoqueen", "Nidoran♂",
    "Nidorino", "Nidoking", "Clefairy", "Clefable",
    "Vulpix", "Ninetales", "Jigglypuff", "Wigglytuff",
    "Zubat", "Golbat", "Oddish", "Gloom",
    "Vileplume", "Paras", "Parasect", "Venonat",
    "Venomoth", "Diglett", "Dugtrio", "Meowth",
    "Persian", "Psyduck", "Golduck", "Mankey",
    "Primeape", "Growlithe", "Arcanine", "Poliwag",
    "Poliwhirl", "Poliwrath", "Abra", "Kadabra",
    "Alakazam", "Machop", "Machoke", "Machamp",
    "Bellsprout", "Weepinbell", "Victreebel", "Tentacool",
    "Tentacruel", "Geodude", "Graveler", "Golem",
    "Ponyta", "Rapidash", "Slowpoke", "Slowbro",
    "Magnemite", "Magneton", "Farfetch’d", "Doduo",
    "Dodrio", "Seel", "Dewgong", "Grimer",
    "Muk", "Shellder", "Cloyster", "Gastly",
    "Haunter", "Gengar", "Onix", "Drowzee",
    "Hypno", "Krabby", "Kingler", "Voltorb",
    "Electrode", "Exeggcute", "Exeggutor", "Cubone",
    "Marowak", "Hitmonlee", "Hitmonchan", "Lickitung",
    "Koffing", "Weezing", "Rhyhorn", "Rhydon",
    "Chansey", "Tangela", "Kangaskhan", "Horsea",
    "Seadra", "Goldeen", "Seaking", "Staryu",
    "Starmie", "Mr. Mime", "Scyther", "Jynx",
    "Electabuzz", "Magmar", "Pinsir", "Tauros",
    "Magikarp", "Gyarados", "Lapras", "Ditto",
    "Eevee", "Vaporeon", "Jolteon", "Flareon",
    "Porygon", "Omanyte", "Omastar", "Kabuto",
    "Kabutops", "Aerodactyl", "Snorlax", "Articuno",
    "Zapdos", "Moltres", "Dratini", "Dragonair",
    "Dragonite", "Mewtwo", "Mew", "Chikorita",
    "Bayleef", "Meganium", "Cyndaquil", "Quilava",
    "Typhlosion", "Totodile", "Croconaw", "Feraligatr",
    "Sentret", "Furret", "Hoothoot", "Noctowl",
    "Ledyba", "Ledian", "Spinarak", "Ariados",
    "Crobat", "Chinchou", "Lanturn", "Pichu",
    "Cleffa", "Igglybuff", "Togepi", "Togetic",
    "Natu", "Xatu", "Mareep", "Flaaffy",
    "Ampharos", "Bellossom", "Marill", "Azumarill",
    "Sudowoodo", "Politoed", "Hoppip", "Skiploom",
    "Jumpluff", "Aipom", "Sunkern", "Sunflora",
    "Yanma", "Wooper", "Quagsire", "Espeon",
    "Umbreon", "Murkrow", "Slowking", "Misdreavus",
    "Unown-A", "Wobbuffet", "Girafarig", "Pineco",
    "Forretress", "Dunsparce", "Gligar", "Steelix",
    "Snubbull", "Granbull", "Qwilfish", "Scizor",
    "Shuckle", "Heracross", "Sneasel", "Teddiursa",
    "Ursaring", "Slugma", "Magcargo", "Swinub",
    "Piloswine", "Corsola", "Remoraid", "Octillery",
    "Delibird", "Mantine", "Skarmory", "Houndour",
    "Houndoom", "Kingdra", "Phanpy", "Donphan",
    "Porygon2", "Stantler", "Smeargle", "Tyrogue",
    "Hitmontop", "Smoochum", "Elekid", "Magby",
    "Miltank", "Blissey", "Raikou", "Entei",
    "Suicune", "Larvitar", "Pupitar", "Tyranitar",
    "Lugia", "Ho-Oh", "Celebi", "Treecko",
    "Grovyle", "Sceptile", "Torchic", "Combusken",
    "Blaziken", "Mudkip", "Marshtomp", "Swampert",
    "Poochyena", "Mightyena", "Zigzagoon", "Linoone",
    "Wurmple", "Silcoon", "Beautifly", "Cascoon",
    "Dustox", "Lotad", "Lombre", "Ludicolo",
    "Seedot", "Nuzleaf", "Shiftry", "Taillow",
    "Swellow", "Wingull", "Pelipper", "Ralts",
    "Kirlia", "Gardevoir", "Surskit", "Masquerain",
    "Shroomish", "Breloom", "Slakoth", "Vigoroth",
    "Slaking", "Nincada", "Ninjask", "Shedinja",
    "Whismur", "Loudred", "Exploud", "Makuhita",
    "Hariyama", "Azurill", "Nosepass", "Skitty",
    "Delcatty", "Sableye", "Mawile", "Aron",
    "Lairon", "Aggron", "Meditite", "Medicham",
    "Electrike", "Manectric", "Plusle", "Minun",
    "Volbeat", "Illumise", "Roselia", "Gulpin",
    "Swalot", "Carvanha", "Sharpedo", "Wailmer",
    "Wailord", "Numel", "Camerupt", "Torkoal",
    "Spoink", "Grumpig", "Spinda", "Trapinch",
    "Vibrava", "Flygon", "Cacnea", "Cacturne",
    "Swablu", "Altaria", "Zangoose", "Seviper",
    "Lunatone", "Solrock", "Barboach", "Whiscash",
    "Corphish", "Crawdaunt", "Baltoy", "Claydol",
    "Lileep", "Cradily", "Anorith", "Armaldo",
    "Feebas", "Milotic", "Castform", "Kecleon",
    "Shuppet", "Banette", "Duskull", "Dusclops",
    "Tropius", "Chimecho", "Absol", "Wynaut",
    "Snorunt", "Glalie", "Spheal", "Sealeo",
    "Walrein", "Clamperl", "Huntail", "Gorebyss",
    "Relicanth", "Luvdisc", "Bagon", "Shelgon",
    "Salamence", "Beldum", "Metang", "Metagross",
    "Regirock", "Regice", "Registeel", "Latias",
    "Latios", "Kyogre", "Groudon", "Rayquaza",
    "Jirachi", "Deoxys", "Turtwig", "Grotle",
    "Torterra", "Chimchar", "Monferno", "Infernape",
    "Piplup", "Prinplup", "Empoleon", "Starly",
    "Staravia", "Staraptor", "Bidoof", "Bibarel",
    "Kricketot", "Kricketune", "Shinx", "Luxio",
    "Luxray", "Budew", "Roserade", "Cranidos",
    "Rampardos", "Shieldon", "Bastiodon", "Burmy-Plant",
    "Wormadam-Plant", "Mothim", "Combee", "Vespiquen",
    "Pachirisu", "Buizel", "Floatzel", "Cherubi",
    "Cherrim", "Shellos-West", "Gastrodon-West", "Ambipom",
    "Drifloon", "Drifblim", "Buneary", "Lopunny",
    "Mismagius", "Honchkrow", "Glameow", "Purugly",
    "Chingling", "Stunky", "Skuntank", "Bronzor",
    "Bronzong", "Bonsly", "Mime Jr.", "Happiny",
    "Chatot", "Spiritomb", "Gible", "Gabite",
    "Garchomp", "Munchlax", "Riolu", "Lucario",
    "Hippopotas", "Hippowdon", "Skorupi", "Drapion",
    "Croagunk", "Toxicroak", "Carnivine", "Finneon",
    "Lumineon", "Mantyke", "Snover", "Abomasnow",
    "Weavile", "Magnezone", "Lickilicky", "Rhyperior",
    "Tangrowth", "Electivire", "Magmortar", "Togekiss",
    "Yanmega", "Leafeon", "Glaceon", "Gliscor",
    "Mamoswine", "Porygon-Z", "Gallade", "Probopass",
    "Dusknoir", "Froslass", "Rotom", "Uxie",
    "Mesprit", "Azelf", "Dialga", "Palkia",
    "Heatran", "Regigigas", "Giratina", "Cresselia",
    "Phione", "Manaphy", "Darkrai", "Shaymin",
    "Arceus", "Victini", "Snivy", "Servine",
    "Serperior", "Tepig", "Pignite", "Emboar",
    "Oshawott", "Dewott", "Samurott", "Patrat",
    "Watchog", "Lillipup", "Herdier", "Stoutland",
    "Purrloin", "Liepard", "Pansage", "Simisage",
    "Pansear", "Simisear", "Panpour", "Simipour",
    "Munna", "Musharna", "Pidove", "Tranquill",
    "Unfezant", "Blitzle", "Zebstrika", "Roggenrola",
    "Boldore", "Gigalith", "Woobat", "Swoobat",
    "Drilbur", "Excadrill", "Audino", "Timburr",
    "Gurdurr", "Conkeldurr", "Tympole", "Palpitoad",
    "Seismitoad", "Throh", "Sawk", "Sewaddle",
    "Swadloon", "Leavanny", "Venipede", "Whirlipede",
    "Scolipede", "Cottonee", "Whimsicott", "Petilil",
    "Lilligant", "Basculin-Red", "Sandile", "Krokorok",
    "Krookodile", "Darumaka", "Darmanitan", "Maractus",
    "Dwebble", "Crustle", "Scraggy", "Scrafty",
    "Sigilyph", "Yamask", "Cofagrigus", "Tirtouga",
    "Carracosta", "Archen", "Archeops", "Trubbish",
    "Garbodor", "Zorua", "Zoroark", "Minccino",
    "Cinccino", "Gothita", "Gothorita", "Gothitelle",
    "Solosis", "Duosion", "Reuniclus", "Ducklett",
    "Swanna", "Vanillite", "Vanillish", "Vanilluxe",
    "Deerling-Spring", "Sawsbuck-Spring", "Emolga", "Karrablast",
    "Escavalier", "Foongus", "Amoonguss", "Frillish",
    "Jellicent", "Alomomola", "Joltik", "Galvantula",
    "Ferroseed", "Ferrothorn", "Klink", "Klang",
    "Klinklang", "Tynamo", "Eelektrik", "Eelektross",
    "Elgyem", "Beheeyem", "Litwick", "Lampent",
    "Chandelure", "Axew", "Fraxure", "Haxorus",
    "Cubchoo", "Beartic", "Cryogonal", "Shelmet",
    "Accelgor", "Stunfisk", "Mienfoo", "Mienshao",
    "Druddigon", "Golett", "Golurk", "Pawniard",
    "Bisharp", "Bouffalant", "Rufflet", "Braviary",
    "Vullaby", "Mandibuzz", "Heatmor", "Durant",
    "Deino", "Zweilous", "Hydreigon", "Larvesta",
    "Volcarona", "Cobalion", "Terrakion", "Virizion",
    "Tornadus", "Thundurus", "Reshiram", "Zekrom",
    "Landorus", "Kyurem", "Keldeo", "Meloetta",
    "Genesect", "Chespin", "Quilladin", "Chesnaught",
    "Fennekin", "Braixen", "Delphox", "Froakie",
    "Frogadier", "Greninja", "Bunnelby", "Diggersby",
    "Fletchling", "Fletchinder", "Talonflame", "Scatterbug",
    "Spewpa", "Vivillon-Icy Snow", "Litleo", "Pyroar",
    "Flabébé-Red", "Floette-Red", "Florges-Red", "Skiddo",
    "Gogoat", "Pancham", "Pangoro", "Furfrou",
    "Espurr", "Meowstic", "Honedge", "Doublade",
    "Aegislash-Shield", "Spritzee", "Aromatisse", "Swirlix",
    "Slurpuff", "Inkay", "Malamar", "Binacle",
    "Barbaracle", "Skrelp", "Dragalge", "Clauncher",
    "Clawitzer", "Helioptile", "Heliolisk", "Tyrunt",
    "Tyrantrum", "Amaura", "Aurorus", "Sylveon",
    "Hawlucha", "Dedenne", "Carbink", "Goomy",
    "Sliggoo", "Goodra", "Klefki", "Phantump",
    "Trevenant", "Pumpkaboo", "Gourgeist", "Bergmite",
    "Avalugg", "Noibat", "Noivern", "Xerneas",
    "Yveltal", "Zygarde", "Diancie", "Hoopa",
    "Volcanion", "Rowlet", "Dartrix", "Decidueye",
    "Litten", "Torracat", "Incineroar", "Popplio",
    "Brionne", "Primarina", "Pikipek", "Trumbeak",
    "Toucannon", "Yungoos", "Gumshoos", "Grubbin",
    "Charjabug", "Vikavolt", "Crabrawler", "Crabominable",
    "Oricorio", "Cutiefly", "Ribombee", "Rockruff",
    "Lycanroc", "Wishiwashi", "Mareanie", "Toxapex",
    "Mudbray", "Mudsdale", "Dewpider", "Araquanid",
    "Fomantis", "Lurantis", "Morelull", "Shiinotic",
    "Salandit", "Salazzle", "Stufful", "Bewear",
    "Bounsweet", "Steenee", "Tsareena", "Comfey",
    "Oranguru", "Passimian", "Wimpod", "Golisopod",
    "Sandygast", "Palossand", "Pyukumuku", "Type: Null",
    "Silvally", "Minior-M-Red", "Komala", "Turtonator",
    "Togedemaru", "Mimikyu", "Bruxish", "Drampa",
    "Dhelmise", "Jangmo-o", "Hakamo-o", "Kommo-o",
    "Tapu Koko", "Tapu Lele", "Tapu Bulu", "Tapu Fini",
    "Cosmog", "Cosmoem", "Solgaleo", "Lunala",
    "Nihilego", "Buzzwole", "Pheromosa", "Xurkitree",
    "Celesteela", "Kartana", "Guzzlord", "Necrozma",
    "Magearna", "Marshadow", "Poipole", "Naganadel",
    "Stakataka", "Blacephalon", "Zeraora", "Meltan",
    "Melmetal", "Grookey", "Thwackey", "Rillaboom",
    "Scorbunny", "Raboot", "Cinderace", "Sobble",
    "Drizzile", "Inteleon", "Skwovet", "Greedent",
    "Rookidee", "Corvisquire", "Corviknight", "Blipbug",
    "Dottler", "Orbeetle", "Nickit", "Thievul",
    "Gossifleur", "Eldegoss", "Wooloo", "Dubwool",
    "Chewtle", "Drednaw", "Yamper", "Boltund",
    "Rolycoly", "Carkol", "Coalossal", "Applin",
    "Flapple", "Appletun", "Silicobra", "Sandaconda",
    "Cramorant", "Arrokuda", "Barraskewda", "Toxel",
    "Toxtricity", "Sizzlipede", "Centiskorch", "Clobbopus",
    "Grapploct", "Sinistea", "Polteageist", "Hatenna",
    "Hattrem", "Hatterene", "Impidimp", "Morgrem",
    "Grimmsnarl", "Obstagoon", "Perrserker", "Cursola",
    "Sirfetch’d", "Mr. Rime", "Runerigus", "Milcery",
    "Alcremie-Vanilla Cream", "Falinks", "Pincurchin", "Snom",
    "Frosmoth", "Stonjourner", "Eiscue", "Indeedee",
    "Morpeko", "Cufant", "Copperajah", "Dracozolt",
    "Arctozolt", "Dracovish", "Arctovish", "Duraludon",
    "Dreepy", "Drakloak", "Dragapult", "Zacian",
    "Zamazenta", "Eternatus", "Kubfu", "Urshifu-Single Strike",
    "Zarude", "Regieleki", "Regidrago", "Glastrier",
    "Spectrier", "Calyrex", "Wyrdeer", "Kleavor",
    "Ursaluna", "Basculegion", "Sneasler", "Overqwil",
    "Enamorus", "Venusaur-Mega", "Charizard-Mega X", "Charizard-Mega Y",
    "Blastoise-Mega", "Beedrill-Mega", "Pidgeot-Mega", "Alakazam-Mega",
    "Slowbro-Mega", "Gengar-Mega", "Kangaskhan-Mega", "Pinsir-Mega",
    "Gyarados-Mega", "Aerodactyl-Mega", "Mewtwo-Mega X",
    "Mewtwo-Mega Y",
    "Ampharos-Mega", "Steelix-Mega", "Scizor-Mega", "Heracross-Mega",
    "Houndoom-Mega", "Tyranitar-Mega", "Sceptile-Mega", "Blaziken-Mega",
    "Swampert-Mega", "Gardevoir-Mega", "Sableye-Mega", "Mawile-Mega",
    "Aggron-Mega", "Medicham-Mega", "Manectric-Mega", "Sharpedo-Mega",
    "Camerupt-Mega", "Altaria-Mega", "Banette-Mega", "Absol-Mega",
    "Glalie-Mega", "Salamence-Mega", "Metagross-Mega", "Latias-Mega",
    "Latios-Mega", "Lopunny-Mega", "Garchomp-Mega", "Lucario-Mega",
    "Abomasnow-Mega", "Gallade-Mega", "Audino-Mega", "Diancie-Mega",
    "Rayquaza-Mega", "Kyogre-Primal", "Groudon-Primal", "Rattata-Alola",
    "Raticate-Alola", "Raichu-Alola", "Sandshrew-Alola",
    "Sandslash-Alola",
    "Vulpix-Alola", "Ninetales-Alola", "Diglett-Alola", "Dugtrio-Alola",
    "Meowth-Alola", "Persian-Alola", "Geodude-Alola", "Graveler-Alola",
    "Golem-Alola", "Grimer-Alola", "Muk-Alola", "Exeggutor-Alola",
    "Marowak-Alola", "Meowth-Galar", "Ponyta-Galar", "Rapidash-Galar",
    "Slowpoke-Galar", "Slowbro-Galar", "Farfetch’d-Galar",
    "Weezing-Galar",
    "Mr. Mime-Galar", "Articuno-Galar", "Zapdos-Galar", "Moltres-Galar",
    "Slowking-Galar", "Corsola-Galar", "Zigzagoon-Galar",
    "Linoone-Galar",
    "Darumaka-Galar", "Darmanitan-Galar", "Yamask-Galar",
    "Stunfisk-Galar",
    "Growlithe-Hisui", "Arcanine-Hisui", "Voltorb-Hisui",
    "Electrode-Hisui",
    "Typhlosion-Hisui", "Qwilfish-Hisui", "Sneasel-Hisui",
    "Samurott-Hisui",
    "Lilligant-Hisui", "Zorua-Hisui", "Zoroark-Hisui", "Braviary-Hisui",
    "Sliggoo-Hisui", "Goodra-Hisui", "Avalugg-Hisui", "Decidueye-Hisui",
    "Pikachu-Cosplay", "Pikachu-Rock Star", "Pikachu-Belle",
    "Pikachu-Pop Star",
    "Pikachu-PhD", "Pikachu-Libre", "Pikachu-Original", "Pikachu-Hoenn",
    "Pikachu-Sinnoh", "Pikachu-Unova", "Pikachu-Kalos", "Pikachu-Alola",
    "Pikachu-Partner", "Pikachu-World", "Pichu-Spiky", "Unown-B",
    "Unown-C", "Unown-D", "Unown-E", "Unown-F",
    "Unown-G", "Unown-H", "Unown-I", "Unown-J",
    "Unown-K", "Unown-L", "Unown-M", "Unown-N",
    "Unown-O", "Unown-P", "Unown-Q", "Unown-R",
    "Unown-S", "Unown-T", "Unown-U", "Unown-V",
    "Unown-W", "Unown-X", "Unown-Y", "Unown-Z",
    "Unown-!", "Unown-?", "Castform-Sunny", "Castform-Rainy",
    "Castform-Snowy", "Deoxys-Attack", "Deoxys-Defense", "Deoxys-Speed",
    "Burmy-Sandy", "Burmy-Trash", "Wormadam-Sandy", "Wormadam-Trash",
    "Cherrim-Sunshine", "Shellos-East", "Gastrodon-East", "Rotom-Heat",
    "Rotom-Wash", "Rotom-Frost", "Rotom-Fan", "Rotom-Mow",
    "Dialga-Origin", "Palkia-Origin", "Giratina-Origin", "Shaymin-Sky",
    "Arceus-Fighting", "Arceus-Flying", "Arceus-Poison",
    "Arceus-Ground",
    "Arceus-Rock", "Arceus-Bug", "Arceus-Ghost", "Arceus-Steel",
    "Arceus-Fire", "Arceus-Water", "Arceus-Grass", "Arceus-Electric",
    "Arceus-Psychic", "Arceus-Ice", "Arceus-Dragon", "Arceus-Dark",
    "Arceus-Fairy", "Basculin-Blue", "Basculin-White", "Darmanitan-Zen",
    "Darmanitan-Galar Zen", "Deerling-Summer", "Deerling-Autumn",
    "Deerling-Winter",
    "Sawsbuck-Summer", "Sawsbuck-Autumn", "Sawsbuck-Winter",
    "Tornadus-Therian",
    "Thundurus-Therian", "Landorus-Therian", "Enamorus-Therian",
    "Kyurem-White",
    "Kyurem-Black", "Keldeo-Resolute", "Meloetta-Pirouette",
    "Genesect-Douse",
    "Genesect-Shock", "Genesect-Burn", "Genesect-Chill",
    "Greninja-active",
    "Greninja-Ash", "Vivillon-Polar", "Vivillon-Tundra",
    "Vivillon-Continental",
    "Vivillon-Garden", "Vivillon-Elegant", "Vivillon-Meadow",
    "Vivillon-Modern",
    "Vivillon-Marine", "Vivillon-Archipelago", "Vivillon-High Plains",
    "Vivillon-Sandstorm",
    "Vivillon-River", "Vivillon-Monsoon", "Vivillon-Savanna",
    "Vivillon-Sun",
    "Vivillon-Ocean", "Vivillon-Jungle", "Vivillon-Fancy",
    "Vivillon-Poké Ball",
    "Flabébé-Yellow", "Flabébé-Orange", "Flabébé-Blue",
    "Flabébé-White",
    "Floette-Yellow", "Floette-Orange", "Floette-Blue", "Floette-White",
    "Floette-Eternal", "Florges-Yellow", "Florges-Orange",
    "Florges-Blue",
    "Florges-White", "Furfrou-Heart", "Furfrou-Star", "Furfrou-Diamond",
    "Furfrou-Debutante", "Furfrou-Matron", "Furfrou-Dandy",
    "Furfrou-La Reine",
    "Furfrou-Kabuki", "Furfrou-Pharaoh", "Meowstic-Female",
    "Aegislash-Blade",
    "Pumpkaboo-Small", "Pumpkaboo-Large", "Pumpkaboo-Super",
    "Gourgeist-Small",
    "Gourgeist-Large", "Gourgeist-Super", "Xerneas-Active",
    "Zygarde-10",
    "Zygarde-10", "Zygarde", "Zygarde-Complete", "Hoopa-Unbound",
    "Oricorio-Pom-Pom", "Oricorio-Pa'u ", "Oricorio-Sensu", "Rockruff",
    "Lycanroc-Midnight", "Lycanroc-Dusk", "Wishiwashi-School",
    "Silvally-Fighting",
    "Silvally-Flying", "Silvally-Poison", "Silvally-Ground",
    "Silvally-Rock",
    "Silvally-Bug", "Silvally-Ghost", "Silvally-Steel", "Silvally-Fire",
    "Silvally-Water", "Silvally-Grass", "Silvally-Electric",
    "Silvally-Psychic",
    "Silvally-Ice", "Silvally-Dragon", "Silvally-Dark",
    "Silvally-Fairy",
    "Minior-M-Orange", "Minior-M-Yellow", "Minior-M-Green",
    "Minior-M-Blue",
    "Minior-M-Indigo", "Minior-M-Violet", "Minior-C-Red",
    "Minior-C-Orange",
    "Minior-C-Yellow", "Minior-C-Green", "Minior-C-Blue",
    "Minior-C-Indigo",
    "Minior-C-Violet", "Mimikyu-Busted", "Necrozma-Dusk Mane",
    "Necrozma-Dawn Wings",
    "Necrozma-Ultra", "Magearna-Original", "Cramorant-Gulping",
    "Cramorant-Gorging",
    "Toxtricity-Low Key", "Sinistea-Antique", "Polteageist-Antique",
    "Alcremie-Ruby Cream",
    "Alcremie-Matcha Cream", "Alcremie-Mint Cream",
    "Alcremie-Lemon Cream", "Alcremie-Salted Cream",
    "Alcremie-Ruby Swirl", "Alcremie-Caramel Swirl",
    "Alcremie-Rainbow Swirl", "Eiscue-Noice",
    "Indeedee-Female", "Morpeko-Hangry", "Zacian-Crowned",
    "Zamazenta-Crowned",
    "Eternatus-Eternamax", "Urshifu-Rapid Strike", "Zarude-Dada",
    "Calyrex-Ice",
    "Calyrex-Shadow"
]

_exp_curves = [
    3, 3, 3, 3,
    3, 3, 3, 3,
    3, 0, 0, 0,
    0, 0, 0, 3,
    3, 3, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    3, 3, 3, 3,
    3, 3, 4, 4,
    0, 0, 4, 4,
    0, 0, 3, 3,
    3, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 5, 5, 3,
    3, 3, 3, 3,
    3, 3, 3, 3,
    3, 3, 3, 5,
    5, 3, 3, 3,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 5, 5, 3,
    3, 3, 0, 0,
    0, 0, 0, 0,
    0, 5, 5, 0,
    0, 0, 0, 0,
    0, 0, 5, 5,
    4, 0, 0, 0,
    0, 0, 0, 5,
    5, 0, 0, 0,
    0, 0, 5, 5,
    5, 5, 5, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 5, 5, 5,
    5, 5, 5, 5,
    5, 5, 3, 3,
    3, 3, 3, 3,
    3, 3, 3, 3,
    0, 0, 0, 0,
    4, 4, 4, 4,
    0, 5, 5, 0,
    4, 4, 4, 4,
    0, 0, 3, 3,
    3, 3, 4, 4,
    0, 3, 3, 3,
    3, 4, 3, 3,
    0, 0, 0, 0,
    0, 3, 0, 4,
    0, 0, 0, 0,
    0, 0, 3, 0,
    4, 4, 0, 0,
    3, 5, 3, 0,
    0, 0, 0, 5,
    5, 4, 0, 0,
    4, 5, 5, 5,
    5, 0, 0, 0,
    0, 5, 4, 0,
    0, 0, 0, 0,
    5, 4, 5, 5,
    5, 5, 5, 5,
    5, 5, 3, 3,
    3, 3, 3, 3,
    3, 3, 3, 3,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 3, 3, 3,
    3, 3, 3, 3,
    3, 0, 0, 5,
    5, 5, 0, 0,
    2, 2, 5, 5,
    5, 1, 1, 1,
    3, 3, 3, 2,
    2, 4, 0, 4,
    4, 3, 4, 5,
    5, 5, 0, 0,
    5, 5, 0, 0,
    1, 2, 3, 2,
    2, 5, 5, 2,
    2, 0, 0, 0,
    4, 4, 4, 3,
    3, 3, 3, 3,
    1, 1, 1, 2,
    4, 4, 0, 0,
    2, 2, 0, 0,
    1, 1, 1, 1,
    1, 1, 0, 3,
    4, 4, 4, 4,
    5, 4, 3, 0,
    0, 0, 3, 3,
    3, 1, 1, 1,
    5, 4, 5, 5,
    5, 5, 5, 5,
    5, 5, 5, 5,
    5, 5, 5, 5,
    5, 5, 3, 3,
    3, 3, 3, 3,
    3, 3, 3, 3,
    3, 3, 0, 0,
    3, 3, 3, 3,
    3, 3, 3, 1,
    1, 1, 1, 0,
    0, 0, 3, 3,
    0, 0, 0, 0,
    0, 0, 0, 4,
    2, 2, 0, 0,
    4, 3, 4, 4,
    4, 0, 0, 0,
    0, 0, 0, 4,
    3, 0, 5, 5,
    5, 5, 3, 3,
    5, 5, 5, 5,
    0, 0, 5, 1,
    1, 5, 5, 5,
    3, 0, 0, 5,
    0, 0, 0, 4,
    0, 0, 0, 3,
    5, 0, 5, 0,
    4, 0, 0, 5,
    5, 5, 5, 5,
    5, 5, 5, 5,
    5, 5, 5, 3,
    5, 5, 3, 3,
    3, 3, 3, 3,
    3, 3, 3, 0,
    0, 3, 3, 3,
    0, 0, 0, 0,
    0, 0, 0, 0,
    4, 4, 3, 3,
    3, 0, 0, 3,
    3, 3, 0, 0,
    0, 0, 4, 3,
    3, 3, 3, 3,
    3, 0, 0, 3,
    3, 3, 3, 3,
    3, 0, 0, 0,
    0, 0, 3, 3,
    3, 3, 3, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 3, 3, 4,
    4, 3, 3, 3,
    3, 3, 3, 0,
    0, 5, 5, 5,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 4, 0, 0,
    0, 0, 3, 3,
    3, 5, 5, 5,
    0, 0, 3, 3,
    3, 5, 5, 5,
    0, 0, 0, 0,
    0, 0, 3, 3,
    0, 0, 0, 0,
    0, 0, 5, 5,
    5, 5, 0, 0,
    5, 5, 5, 5,
    5, 5, 5, 5,
    5, 5, 5, 5,
    5, 5, 5, 5,
    5, 3, 3, 3,
    3, 3, 3, 3,
    3, 3, 0, 0,
    3, 3, 3, 0,
    0, 0, 3, 3,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 5,
    5, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 5, 5,
    5, 5, 4, 0,
    0, 0, 0, 0,
    0, 0, 0, 5,
    5, 5, 5, 5,
    5, 3, 3, 3,
    3, 3, 3, 3,
    3, 3, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 4, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    3, 3, 3, 4,
    5, 5, 0, 0,
    0, 0, 4, 5,
    5, 0, 5, 0,
    0, 0, 0, 0,
    0, 5, 5, 5,
    5, 5, 5, 5,
    5, 5, 5, 5,
    5, 5, 5, 5,
    5, 5, 5, 5,
    5, 5, 5, 5,
    5, 5, 5, 5,
    5, 3, 3, 3,
    3, 3, 3, 3,
    3, 3, 0, 0,
    3, 3, 3, 0,
    0, 0, 4, 4,
    0, 0, 0, 0,
    0, 0, 4, 4,
    3, 3, 3, 1,
    1, 1, 0, 0,
    0, 5, 5, 3,
    3, 0, 0, 3,
    3, 0, 0, 5,
    5, 5, 0, 0,
    0, 0, 0, 4,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 5, 5, 4,
    0, 0, 0, 5,
    5, 5, 5, 0,
    5, 5, 5, 5,
    5, 5, 5, 5,
    5, 5, 5, 5,
    5, 5, 5, 0,
    0, 0, 3, 0,
    5, 3, 3, 3,
    3, 0, 3, 3,
    0, 3, 0, 5,
    5, 5, 5, 5,
    3, 0, 0, 5,
    5, 5, 3, 3,
    3, 5, 3, 4,
    5, 0, 5, 5,
    0, 1, 4, 3,
    0, 5, 5, 5,
    5, 0, 5, 3,
    5, 5, 4, 5,
    5, 5, 5, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 3, 3,
    3, 0, 0, 5,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 5, 5, 5,
    0, 4, 0, 0,
    3, 3, 0, 0,
    5, 5, 0, 0,
    3, 0, 3, 3,
    0, 3, 3, 5,
    5, 5, 0, 3,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 5, 5, 5,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    5, 5, 5, 3,
    5, 5, 5, 5,
    5, 5, 5, 5,
    5, 5, 5, 5,
    5, 5, 5, 5,
    5, 0, 0, 3,
    3, 0, 0, 0,
    0, 0, 0, 5,
    5, 5, 5, 5,
    5, 5, 5, 5,
    5, 5, 5, 3,
    3, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 5, 5,
    5, 5, 5, 5,
    0, 0, 0, 0,
    0, 0, 4, 5,
    5, 5, 5, 5,
    5, 5, 5, 5,
    5, 5, 5, 5,
    5, 5, 5, 5,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 5, 5,
    5, 5, 0, 0,
    3, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 5,
    4, 0, 5, 5,
    5, 5, 5, 5,
    5, 5
]

_abilities = [
    ["Overgrow", "", "Chlorophyll"], ["Overgrow", "", "Chlorophyll"],
    ["Overgrow", "", "Chlorophyll"],
    ["Blaze", "", "Solar Power"], ["Blaze", "", "Solar Power"],
    ["Blaze", "", "Solar Power"],
    ["Torrent", "", "Rain Dish"], ["Torrent", "", "Rain Dish"],
    ["Torrent", "", "Rain Dish"],
    ["Shield Dust", "Run Away", ""], ["Shed Skin", "", ""],
    ["Compound Eyes", "", "Tinted Lens"],
    ["Shield Dust", "Run Away", "Run Away"], ["Shed Skin", "", ""],
    ["Swarm", "Sniper", "Sniper"],
    ["Keen Eye", "", ""], ["Keen Eye", "", ""], ["Keen Eye", "", ""],
    ["Run Away", "Guts", "Hustle"],
    ["Run Away", "Guts", "Hustle"], ["Keen Eye", "", "Sniper"],
    ["Keen Eye", "", "Sniper"],
    ["Intimidate", "", "Shed Skin"], ["Intimidate", "", "Shed Skin"],
    ["Static", "", "Lightning Rod"],
    ["Static", "", "Lightning Rod"], ["Sand Veil", "", "Sand Rush"],
    ["Sand Veil", "", "Sand Rush"],
    ["Poison Point", "", "Hustle"], ["Poison Point", "", "Hustle"],
    ["Poison Point", "", "Sheer Force"],
    ["Poison Point", "", "Hustle"], ["Poison Point", "", "Hustle"],
    ["Poison Point", "", "Sheer Force"],
    ["Friend Guard", "Magic Guard", "Friend Guard"],
    ["Unaware", "Magic Guard", "Unaware"],
    ["Flash Fire", "", "Drought"], ["Flash Fire", "", "Drought"],
    ["Cute Charm", "Competitive", "Friend Guard"],
    ["Cute Charm", "Competitive", "Frisk"], ["Inner Focus", "", "Infiltrator"],
    ["Inner Focus", "", "Infiltrator"],
    ["Chlorophyll", "", "Run Away"], ["Chlorophyll", "", "Stench"],
    ["Chlorophyll", "", "Effect Spore"],
    ["Effect Spore", "", "Dry Skin"], ["Effect Spore", "", "Dry Skin"],
    ["Compound Eyes", "Tinted Lens", "Run Away"],
    ["Shield Dust", "Tinted Lens", "Wonder Skin"],
    ["Arena Trap", "", "Sand Force"], ["Arena Trap", "", "Sand Force"],
    ["Pickup", "Technician", "Unnerve"],
    ["Limber", "Technician", "Unnerve"], ["Swift Swim", "", "Cloud Nine"],
    ["Swift Swim", "", "Cloud Nine"],
    ["Vital Spirit", "Anger Point", "Defiant"],
    ["Vital Spirit", "Anger Point", "Defiant"],
    ["Intimidate", "", "Flash Fire"], ["Intimidate", "", "Flash Fire"],
    ["Water Absorb", "Damp", "Swift Swim"],
    ["Water Absorb", "Damp", "Swift Swim"],
    ["Water Absorb", "Damp", "Swift Swim"],
    ["Synchronize", "Inner Focus", "Magic Guard"],
    ["Synchronize", "Inner Focus", "Magic Guard"],
    ["Synchronize", "Inner Focus", "Magic Guard"],
    ["Guts", "No Guard", "Steadfast"],
    ["Guts", "No Guard", "Steadfast"], ["Guts", "No Guard", "Steadfast"],
    ["Chlorophyll", "", "Gluttony"],
    ["Chlorophyll", "", "Gluttony"], ["Chlorophyll", "", "Gluttony"],
    ["Clear Body", "Liquid Ooze", "Rain Dish"],
    ["Clear Body", "Liquid Ooze", "Rain Dish"],
    ["Rock Head", "Sturdy", "Sand Veil"],
    ["Rock Head", "Sturdy", "Sand Veil"], ["Rock Head", "Sturdy", "Sand Veil"],
    ["Flame Body", "", "Flash Fire"],
    ["Flame Body", "", "Flash Fire"], ["Oblivious", "Own Tempo", "Regenerator"],
    ["Oblivious", "Own Tempo", "Regenerator"],
    ["Magnet Pull", "Analytic", "Sturdy"],
    ["Magnet Pull", "Analytic", "Sturdy"],
    ["Keen Eye", "Inner Focus", "Defiant"],
    ["Run Away", "Early Bird", "Tangled Feet"],
    ["Run Away", "Early Bird", "Tangled Feet"],
    ["Thick Fat", "Hydration", "Ice Body"],
    ["Thick Fat", "Hydration", "Ice Body"],
    ["Poison Touch", "Sticky Hold", "Poison Touch"],
    ["Poison Touch", "Sticky Hold", "Poison Touch"],
    ["Shell Armor", "", "Overcoat"], ["Shell Armor", "Skill Link", "Overcoat"],
    ["Levitate", "", ""],
    ["Levitate", "", ""], ["Cursed Body", "", "Levitate"],
    ["Rock Head", "Weak Armor", "Sturdy"],
    ["Insomnia", "", "Bad Dreams"], ["Insomnia", "", "Bad Dreams"],
    ["Sheer Force", "Shell Armor", "Hyper Cutter"],
    ["Sheer Force", "Shell Armor", "Hyper Cutter"],
    ["Soundproof", "Static", "Galvanize"],
    ["Soundproof", "Static", "Galvanize"], ["Chlorophyll", "", "Harvest"],
    ["Chlorophyll", "", "Harvest"],
    ["Rock Head", "Lightning Rod", "Battle Armor"],
    ["Rock Head", "Lightning Rod", "Battle Armor"],
    ["Limber", "Reckless", "Unburden"],
    ["Inner Focus", "Iron Fist", "No Guard"],
    ["Own Tempo", "Oblivious", "Cloud Nine"], ["Levitate", "", "Stench"],
    ["Levitate", "", "Neutralizing Gas"],
    ["Reckless", "Rock Head", "Lightning Rod"],
    ["Reckless", "Rock Head", "Lightning Rod"],
    ["Natural Cure", "Serene Grace", "Healer"],
    ["Chlorophyll", "Leaf Guard", "Regenerator"],
    ["Early Bird", "Inner Focus", "Scrappy"], ["Swift Swim", "Sniper", "Damp"],
    ["Poison Point", "Sniper", "Damp"],
    ["Swift Swim", "Water Veil", "Lightning Rod"],
    ["Swift Swim", "Water Veil", "Lightning Rod"],
    ["Natural Cure", "", "Analytic"], ["Natural Cure", "", "Analytic"],
    ["Soundproof", "Filter", "Technician"],
    ["Swarm", "", "Technician"], ["Oblivious", "Forewarn", "Dry Skin"],
    ["Vital Spirit", "", "Static"],
    ["Flame Body", "Vital Spirit", "Flash Fire"],
    ["Hyper Cutter", "Mold Breaker", "Moxie"],
    ["Intimidate", "", "Sheer Force"], ["Swift Swim", "", "Rattled"],
    ["Intimidate", "", "Moxie"],
    ["Water Absorb", "Shell Armor", "Hydration"], ["Limber", "", "Imposter"],
    ["Run Away", "Adaptability", "Anticipation"],
    ["Water Absorb", "Water Absorb", "Hydration"],
    ["Volt Absorb", "Volt Absorb", "Quick Feet"],
    ["Flash Fire", "Flash Fire", "Guts"],
    ["Trace", "Analytic", "Download"],
    ["Swift Swim", "Shell Armor", "Weak Armor"],
    ["Swift Swim", "Shell Armor", "Weak Armor"],
    ["Swift Swim", "Battle Armor", "Weak Armor"],
    ["Swift Swim", "Battle Armor", "Weak Armor"],
    ["Rock Head", "Unnerve", "Pressure"],
    ["Immunity", "Thick Fat", "Gluttony"], ["Pressure", "", "Snow Cloak"],
    ["Pressure", "", "Static"],
    ["Pressure", "", "Flame Body"], ["Shed Skin", "", "Marvel Scale"],
    ["Shed Skin", "", "Marvel Scale"],
    ["Inner Focus", "", "Multiscale"], ["Pressure", "", "Unnerve"],
    ["Synchronize", "", ""],
    ["Overgrow", "", "Thick Fat"], ["Overgrow", "", "Thick Fat"],
    ["Overgrow", "", "Thick Fat"],
    ["Blaze", "", "Flash Fire"], ["Blaze", "", "Flash Fire"],
    ["Blaze", "", "Flash Fire"],
    ["Torrent", "", "Sheer Force"], ["Torrent", "", "Sheer Force"],
    ["Torrent", "", "Sheer Force"],
    ["Run Away", "Keen Eye", "Frisk"], ["Run Away", "Keen Eye", "Frisk"],
    ["Insomnia", "Keen Eye", "Tinted Lens"],
    ["Insomnia", "Keen Eye", "Tinted Lens"],
    ["Rattled", "Early Bird", "Early Bird"],
    ["Rattled", "Early Bird", "Iron Fist"], ["Swarm", "Insomnia", "Sniper"],
    ["Swarm", "Insomnia", "Sniper"],
    ["Inner Focus", "", "Infiltrator"], ["Volt Absorb", "", "Water Absorb"],
    ["Volt Absorb", "", "Water Absorb"],
    ["Static", "", "Lightning Rod"],
    ["Friend Guard", "Magic Guard", "Friend Guard"],
    ["Cute Charm", "Competitive", "Friend Guard"],
    ["Super Luck", "Serene Grace", "Hustle"],
    ["Super Luck", "Serene Grace", "Hustle"],
    ["Synchronize", "Early Bird", "Magic Bounce"],
    ["Synchronize", "Early Bird", "Magic Bounce"], ["Static", "", ""],
    ["Static", "", ""], ["Static", "", ""],
    ["Chlorophyll", "", "Healer"], ["Thick Fat", "", "Huge Power"],
    ["Thick Fat", "", "Huge Power"],
    ["Sturdy", "Rock Head", "Rock Head"], ["Water Absorb", "Damp", "Drizzle"],
    ["Chlorophyll", "Leaf Guard", "Infiltrator"],
    ["Chlorophyll", "Leaf Guard", "Infiltrator"],
    ["Chlorophyll", "Leaf Guard", "Infiltrator"],
    ["Run Away", "", "Skill Link"],
    ["Chlorophyll", "Solar Power", "Early Bird"],
    ["Chlorophyll", "Solar Power", "Early Bird"],
    ["Compound Eyes", "", "Speed Boost"], ["Damp", "Water Absorb", "Unaware"],
    ["Damp", "Water Absorb", "Unaware"],
    ["Synchronize", "Synchronize", "Magic Bounce"],
    ["Synchronize", "Synchronize", "Inner Focus"],
    ["Insomnia", "", "Prankster"], ["Oblivious", "Own Tempo", "Regenerator"],
    ["Levitate", "", ""],
    ["Levitate", "", ""], ["Shadow Tag", "", "Telepathy"],
    ["Inner Focus", "Early Bird", "Sap Sipper"],
    ["Sturdy", "", "Overcoat"], ["Sturdy", "", "Overcoat"],
    ["Serene Grace", "Run Away", "Rattled"],
    ["Hyper Cutter", "", "Immunity"], ["Rock Head", "Sheer Force", "Sturdy"],
    ["Intimidate", "", "Rattled"],
    ["Intimidate", "", "Quick Feet"], ["Intimidate", "", "Swift Swim"],
    ["Swarm", "", "Technician"],
    ["Sturdy", "Gluttony", "Contrary"], ["Swarm", "Guts", "Moxie"],
    ["Inner Focus", "Keen Eye", "Pickpocket"],
    ["Quick Feet", "", "Honey Gather"], ["Guts", "Unnerve", "Quick Feet"],
    ["Magma Armor", "Flame Body", "Weak Armor"],
    ["Magma Armor", "Flame Body", "Weak Armor"],
    ["Oblivious", "Thick Fat", "Snow Cloak"],
    ["Oblivious", "Thick Fat", "Snow Cloak"],
    ["Hustle", "Natural Cure", "Regenerator"], ["Hustle", "", "Sniper"],
    ["Suction Cups", "", "Sniper"],
    ["Vital Spirit", "Hustle", "Insomnia"],
    ["Swift Swim", "Water Absorb", "Water Veil"],
    ["Keen Eye", "Sturdy", "Weak Armor"],
    ["Early Bird", "Unnerve", "Flash Fire"],
    ["Early Bird", "Unnerve", "Flash Fire"], ["Swift Swim", "Sniper", "Damp"],
    ["Cute Charm", "", "Sand Veil"],
    ["Sturdy", "Battle Armor", "Sand Veil"], ["Trace", "Analytic", "Download"],
    ["Intimidate", "", "Sap Sipper"],
    ["Own Tempo", "Technician", "Moody"], ["Guts", "Steadfast", "Vital Spirit"],
    ["Intimidate", "Technician", "Steadfast"],
    ["Oblivious", "Forewarn", "Hydration"],
    ["Vital Spirit", "", "Static"],
    ["Flame Body", "Vital Spirit", "Flash Fire"],
    ["Thick Fat", "Scrappy", "Sap Sipper"],
    ["Natural Cure", "Serene Grace", "Healer"],
    ["Pressure", "", "Inner Focus"], ["Pressure", "", "Inner Focus"],
    ["Pressure", "", "Inner Focus"],
    ["Guts", "", "Sand Veil"], ["Shed Skin", "", ""],
    ["Unnerve", "", "Sand Stream"],
    ["Pressure", "", "Multiscale"], ["Pressure", "", "Regenerator"],
    ["Natural Cure", "", ""],
    ["Overgrow", "", "Unburden"], ["Overgrow", "", "Unburden"],
    ["Overgrow", "", "Unburden"],
    ["Blaze", "", "Speed Boost"], ["Blaze", "", "Speed Boost"],
    ["Blaze", "", "Speed Boost"],
    ["Torrent", "", "Damp"], ["Torrent", "", "Damp"], ["Torrent", "", "Damp"],
    ["Run Away", "", "Rattled"],
    ["Intimidate", "", "Moxie"], ["Pickup", "Gluttony", "Quick Feet"],
    ["Pickup", "Gluttony", "Quick Feet"],
    ["Shield Dust", "", "Run Away"], ["Shed Skin", "", ""],
    ["Swarm", "", "Rivalry"], ["Shed Skin", "", ""],
    ["Shield Dust", "", "Compound Eyes"],
    ["Swift Swim", "Rain Dish", "Own Tempo"],
    ["Swift Swim", "Rain Dish", "Own Tempo"],
    ["Swift Swim", "Rain Dish", "Own Tempo"],
    ["Chlorophyll", "Early Bird", "Pickpocket"],
    ["Chlorophyll", "Early Bird", "Pickpocket"],
    ["Chlorophyll", "Early Bird", "Pickpocket"], ["Guts", "", "Scrappy"],
    ["Guts", "", "Scrappy"],
    ["Keen Eye", "Hydration", "Rain Dish"],
    ["Keen Eye", "Drizzle", "Rain Dish"],
    ["Synchronize", "Trace", "Telepathy"],
    ["Synchronize", "Trace", "Telepathy"],
    ["Synchronize", "Trace", "Telepathy"], ["Swift Swim", "", "Rain Dish"],
    ["Intimidate", "", "Unnerve"],
    ["Effect Spore", "Poison Heal", "Quick Feet"],
    ["Effect Spore", "Poison Heal", "Technician"],
    ["Truant", "", ""], ["Vital Spirit", "", ""], ["Truant", "", ""],
    ["Compound Eyes", "", "Run Away"],
    ["Speed Boost", "", "Infiltrator"], ["Wonder Guard", "", ""],
    ["Soundproof", "", "Rattled"],
    ["Soundproof", "", "Scrappy"], ["Soundproof", "", "Scrappy"],
    ["Thick Fat", "Guts", "Sheer Force"],
    ["Thick Fat", "Guts", "Sheer Force"], ["Thick Fat", "", "Huge Power"],
    ["Sturdy", "", "Sand Force"],
    ["Normalize", "", ""], ["Normalize", "", ""],
    ["Keen Eye", "Stall", "Prankster"],
    ["Hyper Cutter", "Intimidate", "Sheer Force"],
    ["Heavy Metal", "Rock Head", "Sturdy"],
    ["Heavy Metal", "Rock Head", "Sturdy"],
    ["Heavy Metal", "Rock Head", "Sturdy"],
    ["Pure Power", "", "Inner Focus"], ["Pure Power", "", "Inner Focus"],
    ["Static", "", "Lightning Rod"],
    ["Static", "", "Lightning Rod"], ["Plus", "", "Lightning Rod"],
    ["Minus", "", "Volt Absorb"],
    ["Illuminate", "Swarm", "Prankster"],
    ["Oblivious", "Tinted Lens", "Prankster"],
    ["Natural Cure", "Poison Point", "Leaf Guard"],
    ["Liquid Ooze", "Sticky Hold", "Gluttony"],
    ["Liquid Ooze", "Sticky Hold", "Gluttony"],
    ["Rough Skin", "", "Speed Boost"],
    ["Rough Skin", "", "Speed Boost"], ["Water Veil", "Oblivious", "Pressure"],
    ["Water Veil", "Oblivious", "Pressure"],
    ["Oblivious", "Simple", "Own Tempo"],
    ["Magma Armor", "Solid Rock", "Own Tempo"], ["Shell Armor", "", "Drought"],
    ["Thick Fat", "Own Tempo", "Gluttony"],
    ["Thick Fat", "Own Tempo", "Gluttony"],
    ["Own Tempo", "Tangled Feet", "Contrary"], ["Arena Trap", "", ""],
    ["Levitate", "", ""], ["Levitate", "", ""],
    ["Sand Veil", "", "Water Absorb"], ["Sand Veil", "", "Water Absorb"],
    ["Natural Cure", "", "Cloud Nine"],
    ["Natural Cure", "", "Cloud Nine"], ["Immunity", "", "Toxic Boost"],
    ["Shed Skin", "", "Infiltrator"],
    ["Levitate", "", ""], ["Levitate", "", ""],
    ["Oblivious", "Anticipation", "Hydration"],
    ["Oblivious", "Anticipation", "Hydration"],
    ["Hyper Cutter", "Shell Armor", "Adaptability"],
    ["Hyper Cutter", "Shell Armor", "Adaptability"], ["Levitate", "", ""],
    ["Levitate", "", ""],
    ["Suction Cups", "", "Storm Drain"], ["Suction Cups", "", "Storm Drain"],
    ["Battle Armor", "", "Swift Swim"],
    ["Battle Armor", "", "Swift Swim"], ["Swift Swim", "", ""],
    ["Marvel Scale", "", "Competitive"],
    ["Forecast", "", ""], ["Protean", "", "Color Change"],
    ["Insomnia", "", "Cursed Body"],
    ["Insomnia", "", "Cursed Body"], ["Levitate", "", "Frisk"],
    ["Pressure", "", "Frisk"],
    ["Chlorophyll", "Solar Power", "Harvest"], ["Levitate", "", ""],
    ["Pressure", "", "Super Luck"],
    ["Shadow Tag", "", "Telepathy"], ["Inner Focus", "", "Moody"],
    ["Inner Focus", "", "Moody"],
    ["Thick Fat", "Oblivious", "Ice Body"],
    ["Thick Fat", "Oblivious", "Ice Body"],
    ["Thick Fat", "Oblivious", "Ice Body"], ["Shell Armor", "", "Rattled"],
    ["Swift Swim", "", "Water Veil"],
    ["Swift Swim", "", "Hydration"], ["Swift Swim", "Rock Head", "Sturdy"],
    ["Swift Swim", "", "Hydration"],
    ["Rock Head", "", "Sheer Force"], ["Rock Head", "", "Overcoat"],
    ["Intimidate", "", "Moxie"],
    ["Clear Body", "", ""], ["Clear Body", "", ""], ["Clear Body", "", ""],
    ["Clear Body", "", "Sturdy"],
    ["Clear Body", "", "Ice Body"], ["Clear Body", "", "Light Metal"],
    ["Levitate", "", ""], ["Levitate", "", ""],
    ["Drizzle", "", ""], ["Drought", "", ""], ["Air Lock", "", ""],
    ["Serene Grace", "", ""],
    ["Pressure", "", ""], ["Overgrow", "Rock Head", "Shell Armor"],
    ["Overgrow", "Rock Head", "Shell Armor"],
    ["Overgrow", "Rock Head", "Shell Armor"],
    ["Blaze", "Iron Fist", "Vital Spirit"],
    ["Blaze", "Iron Fist", "Vital Spirit"],
    ["Blaze", "Iron Fist", "Vital Spirit"],
    ["Torrent", "Defiant", "Clear Body"], ["Torrent", "Defiant", "Clear Body"],
    ["Torrent", "Defiant", "Clear Body"], ["Keen Eye", "", "Reckless"],
    ["Intimidate", "", "Reckless"],
    ["Intimidate", "", "Reckless"], ["Simple", "Unaware", "Unaware"],
    ["Simple", "Unaware", "Unaware"],
    ["Shed Skin", "", "Run Away"], ["Swarm", "", "Technician"],
    ["Intimidate", "", "Guts"],
    ["Intimidate", "", "Guts"], ["Intimidate", "", "Guts"],
    ["Natural Cure", "Poison Point", "Leaf Guard"],
    ["Natural Cure", "Technician", "Leaf Guard"],
    ["Mold Breaker", "", "Sheer Force"],
    ["Mold Breaker", "", "Sheer Force"], ["Sturdy", "", "Soundproof"],
    ["Sturdy", "", "Soundproof"],
    ["Shed Skin", "", "Overcoat"], ["Anticipation", "", "Overcoat"],
    ["Swarm", "", "Tinted Lens"],
    ["Honey Gather", "Honey Gather", "Hustle"], ["Unnerve", "", "Pressure"],
    ["Run Away", "Pickup", "Volt Absorb"],
    ["Swift Swim", "Water Veil", "Swift Swim"],
    ["Swift Swim", "Water Veil", "Swift Swim"], ["Chlorophyll", "", ""],
    ["Flower Gift", "", ""], ["Sticky Hold", "Sand Force", "Storm Drain"],
    ["Sticky Hold", "Sand Force", "Storm Drain"],
    ["Technician", "", "Skill Link"],
    ["Aftermath", "Unburden", "Flare Boost"],
    ["Aftermath", "Unburden", "Flare Boost"],
    ["Cute Charm", "Limber", "Limber"], ["Cute Charm", "Limber", "Limber"],
    ["Levitate", "", ""],
    ["Insomnia", "", "Super Luck"], ["Limber", "Own Tempo", "Keen Eye"],
    ["Thick Fat", "Own Tempo", "Defiant"],
    ["Levitate", "", ""], ["Keen Eye", "Aftermath", "Stench"],
    ["Keen Eye", "Aftermath", "Stench"],
    ["Levitate", "Heatproof", "Heavy Metal"],
    ["Levitate", "Heatproof", "Heavy Metal"],
    ["Sturdy", "Rock Head", "Rock Head"],
    ["Soundproof", "Filter", "Technician"],
    ["Natural Cure", "Serene Grace", "Friend Guard"],
    ["Keen Eye", "Tangled Feet", "Big Pecks"],
    ["Pressure", "", "Infiltrator"], ["Rough Skin", "", "Sand Veil"],
    ["Rough Skin", "", "Sand Veil"],
    ["Rough Skin", "", "Sand Veil"], ["Pickup", "Thick Fat", "Gluttony"],
    ["Steadfast", "Inner Focus", "Prankster"],
    ["Steadfast", "Inner Focus", "Justified"],
    ["Sand Stream", "", "Sand Force"], ["Sand Stream", "", "Sand Force"],
    ["Battle Armor", "", "Sniper"], ["Battle Armor", "", "Sniper"],
    ["Poison Touch", "", "Dry Skin"],
    ["Poison Touch", "", "Dry Skin"], ["Levitate", "", ""],
    ["Swift Swim", "Water Veil", "Storm Drain"],
    ["Swift Swim", "Water Veil", "Storm Drain"],
    ["Swift Swim", "Water Absorb", "Water Veil"],
    ["Soundproof", "", "Snow Warning"], ["Soundproof", "", "Snow Warning"],
    ["Inner Focus", "Pressure", "Pickpocket"],
    ["Magnet Pull", "Analytic", "Sturdy"],
    ["Own Tempo", "Oblivious", "Cloud Nine"],
    ["Solid Rock", "Rock Head", "Lightning Rod"],
    ["Chlorophyll", "Leaf Guard", "Regenerator"],
    ["Vital Spirit", "", "Motor Drive"],
    ["Flame Body", "Vital Spirit", "Flash Fire"],
    ["Super Luck", "Serene Grace", "Hustle"],
    ["Tinted Lens", "", "Speed Boost"],
    ["Leaf Guard", "Leaf Guard", "Chlorophyll"],
    ["Snow Cloak", "Snow Cloak", "Ice Body"],
    ["Hyper Cutter", "", "Poison Heal"],
    ["Oblivious", "Thick Fat", "Snow Cloak"],
    ["Adaptability", "Analytic", "Download"],
    ["Inner Focus", "", "Justified"], ["Magnet Pull", "", "Sand Force"],
    ["Pressure", "", "Frisk"],
    ["Cursed Body", "", "Snow Cloak"], ["Levitate", "", ""],
    ["Levitate", "", ""], ["Levitate", "", ""],
    ["Levitate", "", ""], ["Pressure", "", "Telepathy"],
    ["Pressure", "", "Telepathy"],
    ["Flash Fire", "", "Flame Body"], ["Slow Start", "", ""],
    ["Pressure", "", "Telepathy"], ["Levitate", "", ""],
    ["Hydration", "", ""], ["Hydration", "", ""], ["Bad Dreams", "", ""],
    ["Natural Cure", "", ""],
    ["Multitype", "", ""], ["Victory Star", "", ""],
    ["Overgrow", "", "Contrary"], ["Overgrow", "", "Contrary"],
    ["Overgrow", "", "Contrary"], ["Blaze", "", "Thick Fat"],
    ["Blaze", "", "Thick Fat"], ["Blaze", "", "Reckless"],
    ["Torrent", "", "Shell Armor"], ["Torrent", "", "Shell Armor"],
    ["Torrent", "", "Shell Armor"],
    ["Run Away", "Keen Eye", "Analytic"],
    ["Illuminate", "Keen Eye", "Analytic"],
    ["Vital Spirit", "Run Away", "Scrappy"],
    ["Intimidate", "Sand Rush", "Scrappy"],
    ["Intimidate", "Sand Rush", "Scrappy"], ["Limber", "Unburden", "Prankster"],
    ["Limber", "Unburden", "Prankster"], ["Gluttony", "", "Overgrow"],
    ["Gluttony", "", "Overgrow"],
    ["Gluttony", "", "Blaze"], ["Gluttony", "", "Blaze"],
    ["Gluttony", "", "Torrent"], ["Gluttony", "", "Torrent"],
    ["Synchronize", "", "Telepathy"], ["Synchronize", "", "Telepathy"],
    ["Big Pecks", "Super Luck", "Rivalry"],
    ["Big Pecks", "Super Luck", "Rivalry"],
    ["Big Pecks", "Super Luck", "Rivalry"],
    ["Lightning Rod", "Motor Drive", "Sap Sipper"],
    ["Lightning Rod", "Motor Drive", "Sap Sipper"],
    ["Weak Armor", "Clear Body", "Sturdy"],
    ["Solid Rock", "Clear Body", "Sturdy"],
    ["Solid Rock", "Clear Body", "Sand Stream"], ["Unaware", "Klutz", "Simple"],
    ["Unaware", "Klutz", "Simple"],
    ["Sand Rush", "Sand Force", "Mold Breaker"],
    ["Sand Rush", "Sand Force", "Mold Breaker"],
    ["Healer", "", "Regenerator"], ["Guts", "Sheer Force", "Iron Fist"],
    ["Guts", "Sheer Force", "Iron Fist"],
    ["Guts", "Sheer Force", "Iron Fist"],
    ["Swift Swim", "Poison Touch", "Water Absorb"],
    ["Swift Swim", "Poison Touch", "Water Absorb"],
    ["Swift Swim", "Poison Touch", "Water Absorb"],
    ["Mold Breaker", "Inner Focus", "Guts"],
    ["Mold Breaker", "Inner Focus", "Sturdy"],
    ["Swarm", "Chlorophyll", "Overcoat"],
    ["Leaf Guard", "Chlorophyll", "Overcoat"],
    ["Swarm", "Chlorophyll", "Overcoat"], ["Poison Point", "", "Speed Boost"],
    ["Poison Point", "", "Speed Boost"],
    ["Poison Point", "", "Speed Boost"],
    ["Prankster", "Infiltrator", "Chlorophyll"],
    ["Prankster", "Infiltrator", "Chlorophyll"],
    ["Chlorophyll", "Own Tempo", "Leaf Guard"],
    ["Chlorophyll", "", "Own Tempo"],
    ["Reckless", "Mold Breaker", "Adaptability"], ["Intimidate", "", "Moxie"],
    ["Intimidate", "", "Moxie"], ["Intimidate", "", "Moxie"],
    ["Hustle", "", "Inner Focus"],
    ["Sheer Force", "", "Zen Mode"], ["Chlorophyll", "", "Storm Drain"],
    ["Sturdy", "Shell Armor", "Weak Armor"],
    ["Sturdy", "Shell Armor", "Weak Armor"],
    ["Shed Skin", "Moxie", "Intimidate"],
    ["Shed Skin", "Moxie", "Intimidate"],
    ["Tinted Lens", "Magic Guard", "Magic Guard"], ["Mummy", "", ""],
    ["Mummy", "", ""], ["Solid Rock", "Swift Swim", "Sturdy"],
    ["Solid Rock", "Swift Swim", "Sturdy"],
    ["Defeatist", "", ""], ["Defeatist", "", ""],
    ["Stench", "Sticky Hold", "Aftermath"],
    ["Stench", "Weak Armor", "Aftermath"], ["Illusion", "", ""],
    ["Illusion", "", ""],
    ["Cute Charm", "Technician", "Skill Link"],
    ["Cute Charm", "Technician", "Skill Link"],
    ["Frisk", "Competitive", "Shadow Tag"],
    ["Frisk", "Competitive", "Shadow Tag"],
    ["Frisk", "Competitive", "Shadow Tag"],
    ["Overcoat", "Magic Guard", "Regenerator"],
    ["Overcoat", "Magic Guard", "Regenerator"],
    ["Overcoat", "Magic Guard", "Regenerator"],
    ["Keen Eye", "Big Pecks", "Hydration"],
    ["Keen Eye", "Big Pecks", "Hydration"],
    ["Ice Body", "Snow Cloak", "Weak Armor"],
    ["Ice Body", "Snow Cloak", "Weak Armor"],
    ["Ice Body", "Snow Warning", "Weak Armor"],
    ["Chlorophyll", "", "Serene Grace"],
    ["Chlorophyll", "", "Serene Grace"], ["Static", "", "Motor Drive"],
    ["No Guard", "Shed Skin", "Shed Skin"],
    ["Overcoat", "Shell Armor", "Shell Armor"],
    ["Effect Spore", "", "Regenerator"],
    ["Effect Spore", "", "Regenerator"], ["Cursed Body", "", "Water Absorb"],
    ["Cursed Body", "", "Water Absorb"],
    ["Healer", "Hydration", "Regenerator"],
    ["Compound Eyes", "Unnerve", "Swarm"],
    ["Compound Eyes", "Unnerve", "Swarm"], ["Anticipation", "", "Iron Barbs"],
    ["Anticipation", "", "Iron Barbs"],
    ["Plus", "Minus", "Clear Body"], ["Plus", "Minus", "Clear Body"],
    ["Plus", "Minus", "Clear Body"],
    ["Levitate", "", ""], ["Levitate", "", ""], ["Levitate", "", ""],
    ["Telepathy", "Synchronize", "Analytic"],
    ["Telepathy", "Synchronize", "Analytic"],
    ["Shadow Tag", "Flame Body", "Flash Fire"],
    ["Shadow Tag", "Flame Body", "Flash Fire"],
    ["Shadow Tag", "Flame Body", "Flash Fire"],
    ["Rivalry", "Mold Breaker", "Unnerve"],
    ["Rivalry", "Mold Breaker", "Unnerve"],
    ["Rivalry", "Mold Breaker", "Unnerve"],
    ["Snow Cloak", "Slush Rush", "Rattled"],
    ["Snow Cloak", "Slush Rush", "Swift Swim"], ["Levitate", "", ""],
    ["Hydration", "Shell Armor", "Overcoat"],
    ["Hydration", "Sticky Hold", "Unburden"], ["Static", "", "Sand Veil"],
    ["Inner Focus", "Regenerator", "Reckless"],
    ["Inner Focus", "Regenerator", "Reckless"],
    ["Rough Skin", "Sheer Force", "Mold Breaker"],
    ["Iron Fist", "Klutz", "No Guard"],
    ["Iron Fist", "Klutz", "No Guard"], ["Defiant", "Inner Focus", "Pressure"],
    ["Defiant", "Inner Focus", "Pressure"],
    ["Reckless", "Sap Sipper", "Soundproof"],
    ["Keen Eye", "Sheer Force", "Hustle"],
    ["Keen Eye", "Sheer Force", "Defiant"],
    ["Big Pecks", "Overcoat", "Weak Armor"],
    ["Big Pecks", "Overcoat", "Weak Armor"],
    ["Gluttony", "Flash Fire", "White Smoke"], ["Swarm", "Hustle", "Truant"],
    ["Hustle", "", ""],
    ["Hustle", "", ""], ["Levitate", "", ""], ["Swarm", "", "Flame Body"],
    ["Swarm", "", "Flame Body"],
    ["Justified", "", ""], ["Justified", "", ""], ["Justified", "", ""],
    ["Prankster", "", "Defiant"],
    ["Prankster", "", "Defiant"], ["Turboblaze", "", ""], ["Teravolt", "", ""],
    ["Sand Force", "", "Sheer Force"],
    ["Pressure", "", ""], ["Justified", "", ""], ["Serene Grace", "", ""],
    ["Download", "", ""],
    ["Overgrow", "", "Bulletproof"], ["Overgrow", "", "Bulletproof"],
    ["Overgrow", "", "Bulletproof"],
    ["Blaze", "", "Magic Guard"], ["Blaze", "", "Magic Guard"],
    ["Blaze", "", "Magic Guard"],
    ["Torrent", "", "Protean"], ["Torrent", "", "Protean"],
    ["Torrent", "", "Protean"],
    ["Cheek Pouch", "", "Huge Power"], ["Cheek Pouch", "", "Huge Power"],
    ["Keen Eye", "", "Gale Wings"],
    ["Flame Body", "", "Gale Wings"], ["Flame Body", "", "Gale Wings"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Shed Skin", "", "Friend Guard"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"], ["Unnerve", "", ""],
    ["Unnerve", "", ""],
    ["Flower Veil", "", "Symbiosis"], ["Flower Veil", "", "Symbiosis"],
    ["Flower Veil", "", "Symbiosis"],
    ["Sap Sipper", "", "Grass Pelt"], ["Sap Sipper", "", "Grass Pelt"],
    ["Iron Fist", "Mold Breaker", "Scrappy"],
    ["Iron Fist", "Mold Breaker", "Scrappy"], ["Fur Coat", "", ""],
    ["Keen Eye", "Infiltrator", "Own Tempo"],
    ["Keen Eye", "Infiltrator", "Prankster"], ["No Guard", "", ""],
    ["No Guard", "", ""], ["Stance Change", "", ""],
    ["Healer", "", "Aroma Veil"], ["Healer", "", "Aroma Veil"],
    ["Sweet Veil", "", "Unburden"],
    ["Sweet Veil", "", "Unburden"], ["Contrary", "Suction Cups", "Infiltrator"],
    ["Contrary", "Suction Cups", "Infiltrator"],
    ["Tough Claws", "Sniper", "Pickpocket"],
    ["Tough Claws", "Sniper", "Pickpocket"],
    ["Poison Point", "", "Adaptability"],
    ["Poison Point", "", "Adaptability"], ["Mega Launcher", "", ""],
    ["Mega Launcher", "", ""],
    ["Dry Skin", "Sand Veil", "Solar Power"],
    ["Dry Skin", "Sand Veil", "Solar Power"],
    ["Strong Jaw", "", "Sturdy"], ["Strong Jaw", "", "Rock Head"],
    ["Refrigerate", "", "Snow Warning"],
    ["Refrigerate", "", "Snow Warning"],
    ["Cute Charm", "Cute Charm", "Pixilate"],
    ["Limber", "Unburden", "Mold Breaker"], ["Cheek Pouch", "Pickup", "Plus"],
    ["Clear Body", "", "Sturdy"],
    ["Gooey", "Hydration", "Sap Sipper"], ["Gooey", "Hydration", "Sap Sipper"],
    ["Gooey", "Hydration", "Sap Sipper"], ["Prankster", "", "Magician"],
    ["Natural Cure", "", "Harvest"],
    ["Natural Cure", "", "Harvest"], ["Frisk", "", "Insomnia"],
    ["Frisk", "", "Insomnia"],
    ["Own Tempo", "Ice Body", "Sturdy"], ["Own Tempo", "Ice Body", "Sturdy"],
    ["Frisk", "Infiltrator", "Telepathy"],
    ["Frisk", "Infiltrator", "Telepathy"], ["Fairy Aura", "", ""],
    ["Dark Aura", "", ""], ["Aura Break", "", ""],
    ["Clear Body", "", ""], ["Magician", "", ""], ["Water Absorb", "", ""],
    ["Overgrow", "", "Long Reach"],
    ["Overgrow", "", "Long Reach"], ["Overgrow", "", "Long Reach"],
    ["Blaze", "", "Intimidate"],
    ["Blaze", "", "Intimidate"], ["Blaze", "", "Intimidate"],
    ["Torrent", "", "Liquid Voice"],
    ["Torrent", "", "Liquid Voice"], ["Torrent", "", "Liquid Voice"],
    ["Keen Eye", "Skill Link", "Pickup"],
    ["Keen Eye", "Skill Link", "Pickup"],
    ["Keen Eye", "Skill Link", "Sheer Force"],
    ["Stakeout", "Strong Jaw", "Adaptability"],
    ["Stakeout", "Strong Jaw", "Adaptability"], ["Swarm", "", ""],
    ["Battery", "", ""], ["Levitate", "", ""],
    ["Hyper Cutter", "Iron Fist", "Anger Point"],
    ["Hyper Cutter", "Iron Fist", "Anger Point"], ["Dancer", "", ""],
    ["Sweet Veil", "Shield Dust", "Honey Gather"],
    ["Sweet Veil", "Shield Dust", "Honey Gather"],
    ["Keen Eye", "Vital Spirit", "Steadfast"],
    ["Sand Rush", "", "Inner Focus"], ["Schooling", "", ""],
    ["Merciless", "Limber", "Regenerator"],
    ["Merciless", "Limber", "Regenerator"],
    ["Tangling Hair", "Inner Focus", "Stamina"],
    ["Tangling Hair", "Inner Focus", "Stamina"], ["Water Bubble", "", ""],
    ["Water Bubble", "", ""],
    ["Leaf Guard", "", "Contrary"], ["Leaf Guard", "", "Contrary"],
    ["Effect Spore", "", "Rain Dish"],
    ["Effect Spore", "", "Rain Dish"], ["Corrosion", "", ""],
    ["Corrosion", "", ""], ["Fluffy", "", ""],
    ["Fluffy", "", ""], ["Sweet Veil", "Oblivious", "Leaf Guard"],
    ["Sweet Veil", "Oblivious", "Leaf Guard"],
    ["Sweet Veil", "Queenly Majesty", "Leaf Guard"],
    ["Triage", "", "Natural Cure"],
    ["Inner Focus", "Telepathy", "Symbiosis"], ["Receiver", "", "Defiant"],
    ["Wimp Out", "", ""],
    ["Emergency Exit", "", ""], ["Water Compaction", "", "Sand Veil"],
    ["Water Compaction", "", "Sand Veil"],
    ["Innards Out", "", "Unaware"], ["Battle Armor", "", ""],
    ["RKS System", "", ""], ["Shields Down", "", ""],
    ["Comatose", "", ""], ["Shell Armor", "", ""], ["Iron Barbs", "", "Sturdy"],
    ["Disguise", "", ""],
    ["Dazzling", "Strong Jaw", "Strong Jaw"],
    ["Berserk", "Sap Sipper", "Cloud Nine"], ["Steelworker", "", ""],
    ["Overcoat", "Soundproof", "Bulletproof"],
    ["Overcoat", "Soundproof", "Bulletproof"],
    ["Overcoat", "Soundproof", "Bulletproof"],
    ["Electric Surge", "", "Telepathy"],
    ["Psychic Surge", "", "Telepathy"], ["Grassy Surge", "", "Telepathy"],
    ["Misty Surge", "", "Telepathy"],
    ["Unaware", "", ""], ["Sturdy", "", ""], ["Full Metal Body", "", ""],
    ["Shadow Shield", "", ""],
    ["Beast Boost", "", ""], ["Beast Boost", "", ""], ["Beast Boost", "", ""],
    ["Beast Boost", "", ""],
    ["Beast Boost", "", ""], ["Beast Boost", "", ""], ["Beast Boost", "", ""],
    ["Prism Armor", "", ""],
    ["Soul-Heart", "", ""], ["Technician", "", ""], ["Beast Boost", "", ""],
    ["Beast Boost", "", ""],
    ["Beast Boost", "", ""], ["Beast Boost", "", ""], ["Volt Absorb", "", ""],
    ["Magnet Pull", "", ""],
    ["Iron Fist", "", ""], ["Overgrow", "", "Grassy Surge"],
    ["Overgrow", "", "Grassy Surge"],
    ["Overgrow", "", "Grassy Surge"], ["Blaze", "", "Libero"],
    ["Blaze", "", "Libero"], ["Blaze", "", "Libero"],
    ["Torrent", "", "Sniper"], ["Torrent", "", "Sniper"],
    ["Torrent", "", "Sniper"],
    ["Cheek Pouch", "", "Gluttony"], ["Cheek Pouch", "", "Gluttony"],
    ["Unnerve", "", "Big Pecks"],
    ["Unnerve", "", "Big Pecks"], ["Mirror Armor", "", "Mirror Armor"],
    ["Swarm", "Compound Eyes", "Telepathy"],
    ["Swarm", "Compound Eyes", "Telepathy"],
    ["Swarm", "Compound Eyes", "Telepathy"],
    ["Run Away", "Unburden", "Stakeout"], ["Run Away", "Unburden", "Stakeout"],
    ["Cotton Down", "", "Regenerator"],
    ["Cotton Down", "", "Regenerator"], ["Fluffy", "Run Away", "Bulletproof"],
    ["Fluffy", "Steadfast", "Bulletproof"],
    ["Strong Jaw", "Shell Armor", "Swift Swim"],
    ["Strong Jaw", "Shell Armor", "Swift Swim"], ["Ball Fetch", "", "Rattled"],
    ["Strong Jaw", "", "Competitive"],
    ["Steam Engine", "Heatproof", "Flash Fire"],
    ["Steam Engine", "Flame Body", "Flash Fire"],
    ["Steam Engine", "Flame Body", "Flash Fire"],
    ["Ripen", "Gluttony", "Bulletproof"],
    ["Ripen", "Gluttony", "Hustle"], ["Ripen", "Gluttony", "Thick Fat"],
    ["Sand Spit", "Shed Skin", "Sand Veil"],
    ["Sand Spit", "Shed Skin", "Sand Veil"], ["Gulp Missile", "", ""],
    ["Swift Swim", "", "Propeller Tail"],
    ["Swift Swim", "", "Propeller Tail"], ["Rattled", "Static", "Klutz"],
    ["Punk Rock", "", "Technician"],
    ["Flame Body", "White Smoke", "Flash Fire"],
    ["Flame Body", "White Smoke", "Flash Fire"],
    ["Limber", "", "Technician"], ["Limber", "", "Technician"],
    ["Weak Armor", "", "Cursed Body"],
    ["Weak Armor", "", "Cursed Body"], ["Synchronize", "", "Magic Bounce"],
    ["Synchronize", "", "Magic Bounce"],
    ["Synchronize", "", "Magic Bounce"], ["Prankster", "", "Pickpocket"],
    ["Prankster", "", "Pickpocket"],
    ["Prankster", "", "Pickpocket"], ["Reckless", "Guts", "Defiant"],
    ["Battle Armor", "Tough Claws", "Steely Spirit"],
    ["Weak Armor", "", "Perish Body"],
    ["Inner Focus", "", "Scrappy"],
    ["Tangled Feet", "Screen Cleaner", "Ice Body"],
    ["Wandering Spirit", "", ""],
    ["Sweet Veil", "", "Aroma Veil"], ["Sweet Veil", "", "Aroma Veil"],
    ["Battle Armor", "", "Defiant"],
    ["Lightning Rod", "", "Electric Surge"], ["Shield Dust", "", "Ice Scales"],
    ["Shield Dust", "", "Ice Scales"],
    ["Power Spot", "", ""], ["Ice Face", "", ""],
    ["Inner Focus", "Synchronize", "Psychic Surge"],
    ["Hunger Switch", "", ""], ["Sheer Force", "Heavy Metal", "Heavy Metal"],
    ["Sheer Force", "Heavy Metal", "Heavy Metal"],
    ["Volt Absorb", "Hustle", "Sand Rush"],
    ["Volt Absorb", "Static", "Slush Rush"],
    ["Water Absorb", "Strong Jaw", "Sand Rush"],
    ["Water Absorb", "Ice Body", "Slush Rush"],
    ["Light Metal", "Heavy Metal", "Stalwart"],
    ["Clear Body", "Infiltrator", "Cursed Body"],
    ["Clear Body", "Infiltrator", "Cursed Body"],
    ["Clear Body", "Infiltrator", "Cursed Body"], ["Intrepid Sword", "", ""],
    ["Dauntless Shield", "", ""],
    ["Pressure", "", ""], ["Inner Focus", "", ""], ["Unseen Fist", "", ""],
    ["Leaf Guard", "", ""],
    ["Transistor", "", ""], ["Dragon's Maw", "", ""],
    ["Chilling Neigh", "", ""], ["Grim Neigh", "", ""],
    ["Unnerve", "", ""], ["Intimidate", "", "Sap Sipper"],
    ["Swarm", "Sheer Force", "Steadfast"],
    ["Guts", "Unnerve", "Bulletproof"],
    ["Swift Swim", "Mold Breaker", "Adaptability"],
    ["Inner Focus", "", "Poison Touch"],
    ["Intimidate", "Poison Point", "Swift Swim"], ["Healer", "", "Contrary"],
    ["Thick Fat", "Thick Fat", ""], ["Tough Claws", "Tough Claws", ""],
    ["Drought", "Drought", ""],
    ["Mega Launcher", "Mega Launcher", ""],
    ["Adaptability", "Adaptability", ""], ["No Guard", "No Guard", ""],
    ["Trace", "Trace", ""], ["Shell Armor", "Shell Armor", ""],
    ["Shadow Tag", "Shadow Tag", ""],
    ["Parental Bond", "Parental Bond", ""], ["Aerilate", "Aerilate", ""],
    ["Mold Breaker", "Mold Breaker", ""],
    ["Tough Claws", "Tough Claws", ""], ["Steadfast", "Steadfast", ""],
    ["Insomnia", "Insomnia", ""],
    ["Mold Breaker", "Mold Breaker", ""], ["Sand Force", "Sand Force", ""],
    ["Technician", "Technician", ""],
    ["Skill Link", "Skill Link", ""], ["Solar Power", "Solar Power", ""],
    ["Sand Stream", "Sand Stream", ""],
    ["Lightning Rod", "Lightning Rod", ""], ["Speed Boost", "Speed Boost", ""],
    ["Swift Swim", "Swift Swim", ""],
    ["Pixilate", "Pixilate", ""], ["Magic Bounce", "Magic Bounce", ""],
    ["Huge Power", "Huge Power", ""],
    ["Filter", "Filter", ""], ["Pure Power", "Pure Power", ""],
    ["Intimidate", "Intimidate", ""],
    ["Strong Jaw", "Strong Jaw", ""], ["Sheer Force", "Sheer Force", ""],
    ["Pixilate", "Pixilate", ""],
    ["Prankster", "Prankster", ""], ["Magic Bounce", "Magic Bounce", ""],
    ["Refrigerate", "Refrigerate", ""],
    ["Aerilate", "Aerilate", ""], ["Tough Claws", "Tough Claws", ""],
    ["Levitate", "Levitate", ""],
    ["Levitate", "Levitate", ""], ["Scrappy", "Scrappy", ""],
    ["Sand Force", "Sand Force", ""],
    ["Adaptability", "Adaptability", ""], ["Snow Warning", "Snow Warning", ""],
    ["Inner Focus", "Inner Focus", ""],
    ["Healer", "Healer", ""], ["Magic Bounce", "Magic Bounce", ""],
    ["Delta Stream", "Delta Stream", ""],
    ["Primordial Sea", "Primordial Sea", ""],
    ["Desolate Land", "Desolate Land", ""],
    ["Gluttony", "Hustle", "Thick Fat"], ["Gluttony", "Hustle", "Thick Fat"],
    ["Surge Surfer", "", ""],
    ["Slush Rush", "", "Snow Cloak"], ["Slush Rush", "", "Snow Cloak"],
    ["Snow Cloak", "", "Snow Warning"],
    ["Snow Cloak", "", "Snow Warning"],
    ["Sand Veil", "Tangling Hair", "Sand Force"],
    ["Sand Veil", "Tangling Hair", "Sand Force"],
    ["Pickup", "Technician", "Rattled"],
    ["Fur Coat", "Technician", "Rattled"],
    ["Magnet Pull", "Rock Head", "Galvanize"],
    ["Magnet Pull", "Rock Head", "Galvanize"],
    ["Magnet Pull", "Rock Head", "Galvanize"],
    ["Poison Touch", "Gluttony", "Power of Alchemy"],
    ["Poison Touch", "Gluttony", "Power of Alchemy"],
    ["Harvest", "", ""], ["Cursed Body", "Lightning Rod", "Rock Head"],
    ["Run Away", "Tough Claws", "Unnerve"],
    ["Run Away", "Pastel Veil", "Anticipation"],
    ["Run Away", "Pastel Veil", "Anticipation"],
    ["Gluttony", "Own Tempo", "Regenerator"],
    ["Quick Draw", "Own Tempo", "Regenerator"],
    ["Inner Focus", "", "Scrappy"],
    ["Levitate", "Neutralizing Gas", "Misty Surge"],
    ["Vital Spirit", "Screen Cleaner", "Ice Body"], ["Competitive", "", ""],
    ["Defiant", "", ""],
    ["Berserk", "", ""], ["Curious Medicine", "Own Tempo", "Regenerator"],
    ["Weak Armor", "", "Cursed Body"],
    ["Gluttony", "", "Quick Feet"], ["Gluttony", "", "Quick Feet"],
    ["Hustle", "", "Inner Focus"],
    ["Gorilla Tactics", "", "Zen Mode"], ["Wandering Spirit", "", ""],
    ["Mimicry", "", ""],
    ["Intimidate", "Rock Head", "Flash Fire"],
    ["Intimidate", "Rock Head", "Flash Fire"],
    ["Aftermath", "Static", "Soundproof"],
    ["Aftermath", "Static", "Soundproof"], ["Blaze", "", "Flash Fire"],
    ["Intimidate", "Poison Point", "Swift Swim"],
    ["Inner Focus", "", "Poison Touch"],
    ["Torrent", "", "Shell Armor"], ["Chlorophyll", "Own Tempo", "Hustle"],
    ["Illusion", "", ""],
    ["Illusion", "", ""], ["Keen Eye", "Sheer Force", "Defiant"],
    ["Gooey", "Shell Armor", "Sap Sipper"],
    ["Gooey", "Shell Armor", "Sap Sipper"],
    ["Strong Jaw", "Ice Body", "Sturdy"], ["Overgrow", "", "Long Reach"],
    ["Static", "", "Lightning Rod"], ["Static", "", "Lightning Rod"],
    ["Static", "", "Lightning Rod"],
    ["Static", "", "Lightning Rod"], ["Static", "", "Lightning Rod"],
    ["Static", "", "Lightning Rod"],
    ["Static", "", "Lightning Rod"], ["Static", "", "Lightning Rod"],
    ["Static", "", "Lightning Rod"],
    ["Static", "", "Lightning Rod"], ["Static", "", "Lightning Rod"],
    ["Static", "", "Lightning Rod"],
    ["Static", "", "Lightning Rod"], ["Static", "", "Lightning Rod"],
    ["Static", "", "Lightning Rod"],
    ["Levitate", "", ""], ["Levitate", "", ""], ["Levitate", "", ""],
    ["Levitate", "", ""],
    ["Levitate", "", ""], ["Levitate", "", ""], ["Levitate", "", ""],
    ["Levitate", "", ""],
    ["Levitate", "", ""], ["Levitate", "", ""], ["Levitate", "", ""],
    ["Levitate", "", ""],
    ["Levitate", "", ""], ["Levitate", "", ""], ["Levitate", "", ""],
    ["Levitate", "", ""],
    ["Levitate", "", ""], ["Levitate", "", ""], ["Levitate", "", ""],
    ["Levitate", "", ""],
    ["Levitate", "", ""], ["Levitate", "", ""], ["Levitate", "", ""],
    ["Levitate", "", ""],
    ["Levitate", "", ""], ["Levitate", "", ""], ["Levitate", "", ""],
    ["Forecast", "", ""],
    ["Forecast", "", ""], ["Forecast", "", ""], ["Pressure", "", ""],
    ["Pressure", "", ""],
    ["Pressure", "", ""], ["Shed Skin", "", "Overcoat"],
    ["Shed Skin", "", "Overcoat"],
    ["Anticipation", "", "Overcoat"], ["Anticipation", "", "Overcoat"],
    ["Flower Gift", "", ""],
    ["Sticky Hold", "Sand Force", "Storm Drain"],
    ["Sticky Hold", "Sand Force", "Storm Drain"],
    ["Levitate", "", ""], ["Levitate", "", ""], ["Levitate", "", ""],
    ["Levitate", "", ""],
    ["Levitate", "", ""], ["Pressure", "", "Telepathy"],
    ["Pressure", "", "Telepathy"], ["Levitate", "", ""],
    ["Serene Grace", "", ""], ["Multitype", "", ""], ["Multitype", "", ""],
    ["Multitype", "", ""],
    ["Multitype", "", ""], ["Multitype", "", ""], ["Multitype", "", ""],
    ["Multitype", "", ""],
    ["Multitype", "", ""], ["Multitype", "", ""], ["Multitype", "", ""],
    ["Multitype", "", ""],
    ["Multitype", "", ""], ["Multitype", "", ""], ["Multitype", "", ""],
    ["Multitype", "", ""],
    ["Multitype", "", ""], ["Multitype", "", ""],
    ["Rock Head", "Mold Breaker", "Adaptability"],
    ["Rattled", "Adaptability", "Mold Breaker"],
    ["Sheer Force", "", "Zen Mode"],
    ["Gorilla Tactics", "", "Zen Mode"], ["Chlorophyll", "", "Serene Grace"],
    ["Chlorophyll", "", "Serene Grace"],
    ["Chlorophyll", "", "Serene Grace"], ["Chlorophyll", "", "Serene Grace"],
    ["Chlorophyll", "", "Serene Grace"],
    ["Chlorophyll", "", "Serene Grace"], ["Regenerator", "", ""],
    ["Volt Absorb", "", ""], ["Intimidate", "", ""],
    ["Overcoat", "", ""], ["Turboblaze", "", ""], ["Teravolt", "", ""],
    ["Justified", "", ""],
    ["Serene Grace", "", ""], ["Download", "", ""], ["Download", "", ""],
    ["Download", "", ""],
    ["Download", "", ""], ["Battle Bond", "", ""], ["Battle Bond", "", ""],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Shield Dust", "Compound Eyes", "Friend Guard"],
    ["Flower Veil", "", "Symbiosis"],
    ["Flower Veil", "", "Symbiosis"], ["Flower Veil", "", "Symbiosis"],
    ["Flower Veil", "", "Symbiosis"],
    ["Flower Veil", "", "Symbiosis"], ["Flower Veil", "", "Symbiosis"],
    ["Flower Veil", "", "Symbiosis"],
    ["Flower Veil", "", "Symbiosis"], ["Flower Veil", "", "Symbiosis"],
    ["Flower Veil", "", "Symbiosis"],
    ["Flower Veil", "", "Symbiosis"], ["Flower Veil", "", "Symbiosis"],
    ["Flower Veil", "", "Symbiosis"],
    ["Fur Coat", "", ""], ["Fur Coat", "", ""], ["Fur Coat", "", ""],
    ["Fur Coat", "", ""],
    ["Fur Coat", "", ""], ["Fur Coat", "", ""], ["Fur Coat", "", ""],
    ["Fur Coat", "", ""],
    ["Fur Coat", "", ""], ["Keen Eye", "Infiltrator", "Competitive"],
    ["Stance Change", "", ""],
    ["Frisk", "", "Insomnia"], ["Frisk", "", "Insomnia"],
    ["Frisk", "", "Insomnia"], ["Frisk", "", "Insomnia"],
    ["Frisk", "", "Insomnia"], ["Frisk", "", "Insomnia"],
    ["Fairy Aura", "", ""], ["Aura Break", "", ""],
    ["Power Construct", "", ""], ["Power Construct", "", ""],
    ["Power Construct", "", ""], ["Magician", "", ""],
    ["Dancer", "", ""], ["Dancer", "", ""], ["Dancer", "", ""],
    ["Own Tempo", "", ""],
    ["No Guard", "", "Vital Spirit"], ["Tough Claws", "", ""],
    ["Schooling", "", ""], ["RKS System", "", ""],
    ["RKS System", "", ""], ["RKS System", "", ""], ["RKS System", "", ""],
    ["RKS System", "", ""],
    ["RKS System", "", ""], ["RKS System", "", ""], ["RKS System", "", ""],
    ["RKS System", "", ""],
    ["RKS System", "", ""], ["RKS System", "", ""], ["RKS System", "", ""],
    ["RKS System", "", ""],
    ["RKS System", "", ""], ["RKS System", "", ""], ["RKS System", "", ""],
    ["RKS System", "", ""],
    ["Shields Down", "", ""], ["Shields Down", "", ""],
    ["Shields Down", "", ""], ["Shields Down", "", ""],
    ["Shields Down", "", ""], ["Shields Down", "", ""],
    ["Shields Down", "", ""], ["Shields Down", "", ""],
    ["Shields Down", "", ""], ["Shields Down", "", ""],
    ["Shields Down", "", ""], ["Shields Down", "", ""],
    ["Shields Down", "", ""], ["Disguise", "", ""], ["Prism Armor", "", ""],
    ["Prism Armor", "", ""],
    ["Neuroforce", "", ""], ["Soul-Heart", "", ""], ["Gulp Missile", "", ""],
    ["Gulp Missile", "", ""],
    ["Punk Rock", "", "Technician"], ["Weak Armor", "", "Cursed Body"],
    ["Weak Armor", "", "Cursed Body"],
    ["Sweet Veil", "", "Aroma Veil"], ["Sweet Veil", "", "Aroma Veil"],
    ["Sweet Veil", "", "Aroma Veil"],
    ["Sweet Veil", "", "Aroma Veil"], ["Sweet Veil", "", "Aroma Veil"],
    ["Sweet Veil", "", "Aroma Veil"],
    ["Sweet Veil", "", "Aroma Veil"], ["Sweet Veil", "", "Aroma Veil"],
    ["Ice Face", "", ""],
    ["Own Tempo", "Synchronize", "Psychic Surge"], ["Hunger Switch", "", ""],
    ["Intrepid Sword", "", ""],
    ["Dauntless Shield", "", ""], ["Pressure", "", ""], ["Unseen Fist", "", ""],
    ["Leaf Guard", "", ""],
    ["As One (Glastrier)", "", ""], ["As One (Spectrier)", "", ""]
]

def generate_abilities():
    print("Generating Abilities")

    ability_prefix = "Run&Bun.Ability."

    a = {}
    ab = []
    a["abilities"] = ab

    for pokemon in _abilities:
        for ability in pokemon:
            if ability == "" or ab.__contains__(ability_prefix + game_strings.clean_up(ability)):
                continue

            translations.add_translation(ability_prefix + game_strings.clean_up(ability), ability)
            ab.append(ability_prefix + game_strings.clean_up(ability))

    write_file(os.path.join(directories.get_output_dir("runAndBun"), "rb.abilities"), a)

def generate_dex():
    print("Generating Pokedex")

    dex = dict()

    dex["version"] = "0.7.1"

    form_prefix = "Run&Bun.Form."

    species_ids = dict()
    form_ids = dict()

    entries = []

    for i in range(_pokemon.__len__()):
        entry = dict()
        imports = dict()
        entry["__import"] = imports
        mon = _pokemon[i]
        entry["gameId"] = i + 1
        form = None

        if mon.__contains__('-'):
            if not game_strings.has_species(mon):
                split = mon.split('-')
                mon = split[0]
                form = str.join('-', split[1:])

        if not species_ids.__contains__(mon):
            id = i + 1
            species_ids[mon] = id
            form_ids[id] = 0
        else:
            id = species_ids[mon]
            form_ids[id] += 1

        if form is not None:
            entry["formName"] = form_prefix + game_strings.clean_up(form)
            translations.add_translation(entry["formName"], form)

        entry["growthRate"] = _exp_curves[i]

        ab = []

        for ability in _abilities[i]:
            ab.append(
                "" if ability.strip() == "" else "Run&Bun.Ability." + game_strings.clean_up(
                    ability))

        entry["abilities"] = ab

        if form_ids[id] == 0:
            import_blb = dict()
            imports[
                "pokelink:/pokemon/national/" + str(id) + ".entry"] = import_blb
            import_blb["mergeArrays"] = False

            if id not in (57, 203, 206, 625, 840,
                          884) and core_plugin.file_exists(
                    "/pokemon/national/" + str(id) + ".evos"):
                imports[
                    "pokelink:/pokemon/national/" + str(id) + ".evos"] = None
            elif id == 840:
                imports["pokelink:/pokemon/swsh/" + str(id) + ".evos"] = None

            entry["id"] = entries.__len__() + 1
            entries.append(entry)
        else:
            import_blb = dict()
            import_blb["mergeArrays"] = False
            imports[(
                    "pokelink:/pokemon/national/" + str(
                id) + ".entry") if id in (172, 716, 744) else (
                    "pokelink:/pokemon/national/" + str(id) + "." + str(
                form_ids[
                    id]) + ".entry")] = import_blb

            entry["form"] = form_ids[id]

            for base_entry in entries:
                if base_entry["id"] == id:
                    if not base_entry.__contains__("forms"):
                        base_entry["forms"] = []

                    base_entry["forms"].append(entry)

    dex["entries"] = entries

    write_file(os.path.join(directories.get_output_dir("runAndBun"), "rb.dex"), dex)
